googleapis/synthtool

- CHANGELOG.md
> Release synthtool 0.1.0

- .kokoro/build.sh
- README.md
Change-Id: I55a3c749f1850b8374ddbbcedf8e9382bb353067
> Cleanup build directory to prevent kokoro from choking

- CHANGELOG.md
- setup.py
> Release synthtool 0.2.0

- .kokoro/build.sh
- nox.py
Change-Id: Ibcde6d08ddd057db62b1bc1e5354b7f39dab1594
> Use new Nox

- CHANGELOG.md
- setup.py
> Release synthtool 0.3.0

- CHANGELOG.md
- setup.py
> Release synthtool 0.3.1

- synthtool/sources/templates.py
- tests/test_templates.py
Relevant Jinja2 docs [here](http://jinja.pocoo.org/docs/dev/templates/#whitespace-control)
fixes #25
> set Jinja2 option to keep new line char at EOF

- CHANGELOG.md
- setup.py
> Release synthtool 0.4.0

- CHANGELOG.md
- setup.py
> Release synthtool 0.5.0 - nodejs .kokoro templates

- CHANGELOG.md
- setup.py
> Release synthtool 0.6.0

- CHANGELOG.md
- setup.py
> Release synthtool 0.6.1

- CHANGELOG.md
- setup.py
> Release synthtool 0.6.2

- synthtool/gcp/templates/node_library/.circleci/config.yml.j2
This is the real fix 🤣 After approving, please feel free to merge and cut a release so autosynth doesn't beat me up tomorrow.
> Update CircleCI config for nodejs

- synthtool/sources/templates.py
- synthtool/transforms.py
- tests/fixtures/executable.j2
- tests/test_templates.py
- tests/test_transforms.py
Fixes #46. Pardon my novice python, any edits welcome :)
> Preserve file mode in templates

- synthtool/gcp/templates/node_library/.circleci/config.yml
[nodejs-storage](https://github.com/googleapis/nodejs-storage/commit/e46f69eb82014f50586cd8525e3af7ca15490c29#diff-1d37e48f9ceff6d8030570cd36286a61) had 2 service account keys that needed to be decrypted.
> node: decrypt all service-account keys

- synthtool/gcp/templates/node_library/.circleci/config.yml
Forgot to escape multi-line command 😅
> fix: circle.yml decrypt multiple

- synthtool/gcp/templates/node_library/.kokoro/common.cfg
- synthtool/gcp/templates/node_library/.kokoro/continuous/node10/common.cfg
- synthtool/gcp/templates/node_library/.kokoro/continuous/node6/common.cfg
- synthtool/gcp/templates/node_library/.kokoro/continuous/node8/common.cfg
- synthtool/gcp/templates/node_library/.kokoro/docs.sh
- synthtool/gcp/templates/node_library/.kokoro/lint.sh
- synthtool/gcp/templates/node_library/.kokoro/presubmit/node10/common.cfg
- synthtool/gcp/templates/node_library/.kokoro/presubmit/node6/common.cfg
- synthtool/gcp/templates/node_library/.kokoro/presubmit/node8/common.cfg
- synthtool/gcp/templates/node_library/.kokoro/samples-test.sh
- synthtool/gcp/templates/node_library/.kokoro/system-test.sh
- synthtool/gcp/templates/node_library/.kokoro/test.sh
running npm install under `root` will have issues.
> nodejs: use Docker node version that runs in non-root

- CHANGELOG.md
- setup.py
> Release synthtool 0.7.1

- synthtool/gcp/templates/node_library/.kokoro/presubmit/node8/samples-test.cfg
- synthtool/gcp/templates/node_library/.kokoro/presubmit/node8/system-test.cfg
Run system and samples test on Presubmit (PRs) as well
> feat(node): run system and samples test on Kokoro for nodejs repos

- CHANGELOG.md
- setup.py
> Release synthtool 0.9.0

- CHANGELOG.md
- setup.py
> Release synthtool 0.10.0

- synthtool/gcp/gapic_generator.py
> Construct the artman instance only once.

- synthtool/gcp/artman.py
- synthtool/metadata.py
- synthtool/protos/metadata.proto
- synthtool/protos/metadata_pb2.py
- tests/test_metadata.py
Towards #126.
Metadata now looks like this:
```
{
"sources": [
{
"git": {
"name": "googleapis",
"remote": "https://github.com/googleapis/googleapis.git",
"sha": "5a57f0c13a358b2b15452bf2d67453774a5f6d4f",
"internalRef": "221837528"
}
},
{
"git": {
"name": "googleapis-private",
"remote": "https://github.com/googleapis/googleapis-private.git",
"sha": "6aa8e1a447bb8d0367150356a28cb4d3f2332641",
"internalRef": "221340946"
}
},
{
"generator": {
"name": "artman",
"version": "0.16.0",
"dockerImage": "googleapis/artman@sha256:90f9d15e9bad675aeecd586725bce48f5667ffe7d5fc4d1e96d51ff34304815b"
}
}
]
}
```
> Report Artman info to metadata

- CHANGELOG.md
- setup.py
> Release synthtool 2018.11.27

- CHANGELOG.md
- setup.py
> Release synthtool 2018.11.28

- CHANGELOG.md
- setup.py
> Release synthtool 2018.11.29

- CHANGELOG.md
- setup.py
> Release synthtool 2018.11.30

- synthtool/gcp/templates/node_library/.prettierignore
- synthtool/gcp/templates/node_library/.prettierrc
- synthtool/gcp/templates/node_library/renovate.json
We copy these around to every library today, may as well have them consistenty updated in synthtool :)
> Add renovate and prettier configs to nodejs templates

- CHANGELOG.md
- setup.py
> Release synthtool 2018.12.05

- CHANGELOG.md
- setup.py
> Release synthtool 2018.12.06

- CHANGELOG.md
- setup.py
> Release synthtool 2019.01.16

- synthtool/gcp/templates/node_library/.github/CONTRIBUTING.md
Fixes https://github.com/googleapis/nodejs-bigquery/issues/216
> node: add lint/fix example to contributing guide

- CHANGELOG.md
- setup.py
> Release synthtool 2019.02.26

- README.md
> s/GoogleCloudPlatform/googleapis/g in README

- synthtool/gcp/common.py
> Check 'metadata' in kwargs.

- synthtool/gcp/common.py
- synthtool/gcp/templates/node_library/README.md
organically @callmehiphop has made some great edits to README.md. This modifies our base template to make it lineup.
Now _all_ our libraries can move towards this straight-forward standard.
> chore: improve the README template

- synthtool/gcp/templates/node_library/samples/README.md
copy edits based on conversation [here](https://github.com/googleapis/nodejs-storage/pull/649).
> docs: copy in samples/README.md read poorly

- CHANGELOG.md
- setup.py
> Release synthtool 2019.04.10

- README.md
> Run with python3

- CHANGELOG.md
- setup.py
> Release synthtool 2019.05.02

- synthtool/gcp/templates/node_library/.kokoro/release/docs.cfg
- synthtool/gcp/templates/node_library/.kokoro/release/docs.sh
there will be a mass PR adding this, which we can merge before landing this.
> build: add job for publishing docs to googleapis.dev

- synthtool/gcp/templates/node_library/.kokoro/continuous/node12/common.cfg
- synthtool/gcp/templates/node_library/.kokoro/presubmit/node12/common.cfg
I am going to land this post-hoc, after we've already created a PR on all Node.js repos.
> feat: add Node@12 to test matrix (remove 11)

- synthtool/gcp/templates/java_library/.github/ISSUE_TEMPLATE/bug_report.md
- synthtool/gcp/templates/java_library/.github/ISSUE_TEMPLATE/feature_request.md
See https://github.com/googleapis/google-api-java-client/pull/1353
> Java address feedback for issue templates

- synthtool/gcp/templates/node_library/.github/release-please.yml
- synthtool/gcp/templates/node_library/.kokoro/continuous/node10/test.cfg
- synthtool/gcp/templates/node_library/.kokoro/test.sh
we now have a GitHub bot that does this, no need to hack it into kokoro.
> build: switching to GitHub app for release-please

- synthtool/gcp/templates/node_library/CONTRIBUTING.md
my fault for bad code review, missed a couple typos in the testing instructions.
> docs: tweaks to testing instructions

- synthtool/gcp/gapic_microgenerator.py
this adds support for TypeScript library generation via the microgenerator :tada: 
thank you for the hard work @xiaozhenliu-gg5 and @alexander-fenster.
> feat: add typescript microgenerator support

- synthtool/gcp/templates/node_library/.jsdoc.js
I'm holding off on landing this until I send a mass PR for all of our repos.
> feat(nodejs): add jsdoc plugin for region tags

- synthtool/gcp/gapic_microgenerator.py
- tests/test_templates.py
- tests/test_transforms.py
Fixes https://github.com/googleapis/synthtool/issues/338
> fix: let nox tests pass on Windows

- synthtool/__main__.py
Fixes https://github.com/googleapis/synthtool/issues/128
> fix: add help text to synthtool command

- synthtool/metadata.py
- tests/test_metadata.py
Fixes https://github.com/googleapis/synthtool/issues/360
> fix: disable obsolete file tracking by default

- synthtool/metadata.py
- tests/test_metadata.py
now that it ignores files ignored by git.
> feat: reenable obsolete file tracking and removal

- synthtool/metadata.py
- tests/test_metadata.py
synthtool and the current repo are both git sources that were not being recorded in the metadata.  Record them.
> feat: add implicit git sources

- synthtool/gcp/templates/java_library/.kokoro/nightly/integration.cfg
- synthtool/gcp/templates/java_library/.kokoro/nightly/samples.cfg
Feature to report to buildcop merged in #420
> feat(java_templates): enable buildcop on nightly samples/integration tests

- synthtool/gcp/templates/java_library/.github/PULL_REQUEST_TEMPLATE.md
This brings the pull request template in line with what's in node and python.   Not sure we can 100% trust the `repo` variable will be populated or not :)
> fix(java): update pull request template

- synthtool/gcp/templates/java_library/samples/install-without-bom/pom.xml
- synthtool/gcp/templates/java_library/samples/snapshot/pom.xml
Also run tests for install-without-bom artifact
> fix(java): fix duplicated artifact in the reactor

- tests/test_language_java.py
> test(java): ensure generated pom.xml files are valid XML

- synthtool/gcp/templates/node_library/README.md
slight tweaks to the wording of our contributing blurb in the README.
> docs: slight tweak to wording of contributing blurb in README

- synthtool/gcp/templates/node_library/.prettierrc.js
Just fix it. I'll take care of the consequences :)
> fix: apache license URL

- synthtool/metadata.py
- tests/test_metadata.py
Partial revert of b37cf74d12e9a42b9de9e61a4f26133d7cd9c168.
> fix: record version of working repo in synth.metadata

- synthtool/gcp/templates/python_library/noxfile.py.j2
https://pypi.org/project/google-cloud-testutils/
> fix(python): install testutils from pypi

- autosynth/change_pusher.py
- autosynth/github.py
- autosynth/synth.py
- tests/test_synth.py
so it will be easy to collect statistics about PRs with context
> chore: add labels with context info

- autosynth/change_pusher.py
- tests/test_change_pusher.py
- tests/testdata/mock-synth-golden-squash-prs.log
for the two trailers we expect merge-on-green bot to consume.
> feat: include trailers in PR body

- autosynth/providers/java_apiary.py
- autosynth/synth.py
- synthtool/sources/templates.py
- tests/test_synth.py
- tests/test_templates.py
Not entirely sure what happened, but linting starting to fail (perhaps a test dependency update?)
> chore: fix f-string linting

- autosynth/executor.py
> fix: fix f-string usage in command debugger

- autosynth/multi.py
> fix: uses http for links to internal logs

- autosynth/multi.py
fixes https://github.com/googleapis/synthtool/issues/560
> fix: hide a few API gen failures from autosynth maintainers

- synthtool/sources/git.py
fixes https://github.com/googleapis/synthtool/issues/509
> fix: --recurse-submodules when cloning repos

- README.md
> chore: fix README instructions for java

- autosynth/git_source.py
- integration_tests/test_git_source.py
- tests/test_git_source.py
fixes https://github.com/googleapis/synthtool/issues/596
> fix: strip PR numbers from commit

- autosynth/change_pusher.py
fixes https://github.com/googleapis/synthtool/issues/333
fixes https://github.com/googleapis/synthtool/issues/277
Confirmed it worked as expected:
https://github.com/googleapis/python-texttospeech/pull/44
> feat: add "regenerate me" checkbox to pull requests

- synthtool/README.md
fix https://github.com/googleapis/synthtool/issues/450
and update instructions to match current process
> docs: improve README

- autosynth/multi.py
- tests/test_multi.py
- tests/testdata/sponge-log-golden.xml
> fix: decode output from individual synth run as utf-8 string

- autosynth/multi.py
Consolidate the collected logs path
> fix: use 'logs' directory for base log path

- noxfile.py
Fixes https://github.com/googleapis/synthtool/issues/325
> fix: run tests and linters with py 3.8 too

- synthtool/gcp/templates/node_library/.kokoro/populate-secrets.sh
Ported for general use from https://github.com/googleapis/nodejs-firestore/pull/1118
> chore(nodejs_templates): add script logging to node_library populate-secrets.sh

- autosynth/synth.py
- tests/test_synth.py
fixes https://github.com/googleapis/synthtool/issues/623
> fix: use a [CHANGE ME] PR title when there's a commit without context

- synthtool/README.md
- synthtool/pydoc.html
fixes https://github.com/googleapis/synthtool/issues/201
> doc: add a pydoc describing common transforms

- synthtool/gcp/templates/java_library/.kokoro/nightly/integration.cfg
- synthtool/gcp/templates/java_library/.kokoro/presubmit/integration.cfg
Also migrating the integration secrets to secret manager.
> ci(java): switch integration test secrets to secret manager

- autosynth/synth.py
- tests/test_synth.py
fixes https://github.com/googleapis/synthtool/issues/638
> fix: let failures to build from a single source fail fast

- synthtool/gcp/templates/node_library/.kokoro/publish.sh
Refs: https://github.com/googleapis/google-api-nodejs-client/pull/2280
> build: missing closing paren in publish script

- .gitattributes
- synthtool/gcp/templates/node_library/.kokoro/release/docs-devsite.cfg
- synthtool/gcp/templates/node_library/.kokoro/release/docs-devsite.sh
- synthtool/gcp/templates/node_library/api-extractor.json
Generate and upload yaml files for ref docs.
> chore: add config files for cloud-rad for node.js

- .kokoro-autosynth/java.cfg
Test out the SYNTHTOOL_TRACK_OBSOLETE_FILES flag
> build(java): enable obsolete file tracking

- synthtool/gcp/templates/python_library/.kokoro/docs/common.cfg
- synthtool/gcp/templates/python_library/.kokoro/publish-docs.sh
Somehow some changes are missing from the template.
> fix(python-library): add missing changes

- synthtool/gcp/snippets.py
- tests/fixtures/snippets/interleaved_with_exclude.js
- tests/test_snippets.py
Will resolve issues seen here: https://github.com/googleapis/java-bigtable/issues/383
> fix: snippet generation with start and end tags within excludes

- synthtool/gcp/templates/node_library/.kokoro/release/docs-devsite.sh
Delete `SharePoint` item from TOC.
> chore: update cloud rad kokoro build job

- synthtool/log.py
https://github.com/googleapis/synthtool/pull/721 failed to resolve the issue.
It turned dialed down logging for everything except watchdog.
I've tested this and confirmed this new code will work.
> fix: really turn off verbose logging from watchdog

- synthtool/gcp/templates/python_library/.kokoro/populate-secrets.sh
- synthtool/gcp/templates/python_library/.kokoro/trampoline.sh
Confirmed with testing in https://github.com/googleapis/python-bigquery-storage/pull/59 that this combo of files along with #758 results in a successful Python release.
> build(python): add secret manager

- synthtool/gcp/templates/python_library/docs/conf.py.j2
Some libraries use this sphinx extension.
> chore(python): add sphinx doctest extension

- synthtool/transforms.py
- tests/fixtures/executable_file.sh
- tests/test_transforms.py
> fix: set the file mode for template file permissions when merging a file

- .github/sync-repo-settings.yaml
> build: grant push permissions to yoshi-* teams

- synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc.sh
Upload from `target/devsite/reference` not `target/devsite`.
@tbpg FYI
> fix(java_library): Update publish_javadoc.sh

- synthtool/gcp/templates/java_library/.github/generated-files-bot.yml
This bot will comment on pull requests that modify templated files. For java, we configure to read from our 2 synth.metadata files: (primary templates and README)
> chore(java): enable generated-files-bot

- synthtool/gcp/templates/java_library/.github/blunderbuss.yml
Sample assigned PR: https://github.com/googleapis/java-vision/pull/332
> build(java): enable blunderbuss for samples

- synthtool/metadata.py
This PR modifies the metadata tracker logic so it runs a watchdog filesystem observer _only_ if obsolete file tracking is enabled. The observer is pointless if tracking is disabled because its results are never used.
Although I can't test it locally, I'm pretty sure this should fix an issue that suddenly caused all Elixir synth jobs to fail starting 2020-12-19 (example: https://github.com/googleapis/elixir-google-api/issues/7085). What seems to be happening is:
* The Elixir synth job deletes (recursively) the parent directory of the watch directory, while the observer is running. (It then regenerates the directory from scratch.) I _think_ this is confusing inotify in such a way as to cause it to throw an Errno when closing its control FD.
* Oddly, this never failed until the 2020-12-19 …
> fix: Don't create an observer unless tracking obsolete files

- synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
In response to the new multi release branch changes.
> build(java): update autorelease branch name check

- synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc11.cfg
java-memcache was set for all accidentally
> fix: update repo name in publish_javadoc11

- synthtool/gcp/templates/java_library/.kokoro/build.sh
- synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
> build: reduce download junk in log files

- synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc11.sh
- also cleaning up uneccessary dash in destination_prefix
> chore: copy README to docfx-yml dir

- docker/owlbot/nodejs/Dockerfile
PubSub subscription was missing upstream, ensure that a new docker container gets pushed.
> build: test docker publish pipeline

- docker/owlbot/nodejs/entrypoint.sh
- synthtool/languages/node.py
This will allow us to remove synth.py _and_ owlbot.py from many nodejs repos.
> feat(node): invoke owlbot_main() where there's no owlbot.py in the repo

- autosynth/change_pusher.py
fixes https://github.com/googleapis/synthtool/issues/978
> fix: tell the user autosynth may take 24 hours to regenerate

- synthtool/gcp/templates/java_library/.kokoro/build.sh
> chore(java): detect sample-secrets in build.sh

- synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc.sh
missed removing when removed v2 solution - https://github.com/googleapis/synthtool/pull/964
> chore: remove STAGING_BUCKET_V2 check

- synthtool/gcp/snippets.py
- tests/fixtures/snippets/reused.js
- tests/test_snippets.py
> fix: snippet parser should handle reused region tags

- synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc11.sh
Adding version history to docs
> chore: add changelog to cloud-rad

- synthtool/gcp/templates/java_library/README.md
Add policy from https://cloud.google.com/java/docs/supported-java-versions
> chore(docs): update README.md to add java support policy

- synthtool/languages/java.py
Here's an alternate implementation which splits into add_javadoc and annotation_method
> refactor: alternative of splitting into add_javadoc and annotate_method

- docker/owlbot/java/src/fix-poms.py
> chore(java): don't mess with poms for non-client library repos

- docker/owlbot/java/Dockerfile
- docker/owlbot/java/container_test.yaml
Reverts googleapis/synthtool#1288
> Revert "deps: upgrade google-java-format to 1.13.0"

- synthtool/languages/php.py
- tests/test_php.py
> chore: fix php post processor

- synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
https://github.com/actions/github-script#breaking-changes-in-v5
> chore: update auto-release script to fix breaking changes in v5

- synthtool/gcp/templates/java_library/.github/workflows/approve-readme.yaml
- synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
- synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
- synthtool/gcp/templates/java_library/.github/workflows/samples.yaml
update actions/checkout to v3
update actions/setup-java to v3
update actions/github-script to v6
> chore: update github actions

- synthtool/gcp/templates/java_library/README.md
Fix https://github.com/googleapis/google-cloud-java/issues/9223 and https://github.com/googleapis/google-cloud-java/issues/9220
> chore: fix broken links in `README.md`

- docker/owlbot/java/src/fix-poms.py
Fix https://github.com/googleapis/google-cloud-java/issues/9304
> chore: make exception for non-cloud artifacts

- synthtool/gcp/templates/java_library/.github/dependabot.yml
Fixing the configuration for `ignore` property. [Reference documentation.](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore)
> chore: Update dependabot.yml

- synthtool/gcp/templates/java_library/.github/workflows/approve-readme.yaml
- synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
- synthtool/gcp/templates/java_library/.github/workflows/renovate_config_check.yaml
- synthtool/gcp/templates/java_library/.github/workflows/samples.yaml
Update dependency versions for actions/github-script, actions/checkout, and actions/setup-java@v4
> chore: update dependency versions in java templates
