synthtool/gcp/templates/node_library/.circleci/config.yml.j2
otherwise initial `npm publish` doesn't work because npm defaults scoped packages published to be private.
=> [NodeJS] Add --access=public to circle config

synthtool/transforms.py
Feature request for synthtool. During file copy, allows the result to be a "merge" of the contents of the source and the existing destination file. The merge function itself is provided as an optional argument to `transforms.move`.
One use case supported by this feature the ruby gemspec. This file specifies, among other things, the gem version, and the library dependencies. The former is updated during the release process (i.e. GAPIC does not know what version the gem currently is, so it cannot generate that part of the file correctly). The latter should be controlled by GAPIC (e.g. only GAPIC knows what version of google-gax its generated code depends on). Thus, the final gemspec output by synth must include the current version from the existing gemspec, and the dependency information …
=> Support optional merge function during copy

synthtool/sources/git.py
Automatically track all cloned git repo paths. Many code generators operate within their own repository and do not provide an option for where the generated code is placed. For these synth scripts, the user can use the `git` and `shell` tools to run the codegen process. The output files need to be in a tracked path or they cannot be found and the user should not be setting `_tracked_paths` themselves.
This PR makes #27 unnecessary.
=> Add git sources to tracked_paths

synthtool/gcp/common.py, synthtool/gcp/templates/php_library/CONTRIBUTING.md, synthtool/gcp/templates/php_library/phpunit-snippets.xml.dist, synthtool/gcp/templates/php_library/phpunit-system.xml.dist, synthtool/gcp/templates/php_library/phpunit.xml.dist
Not sure if this is the best design, but I'm following what nodejs did. Please take a look.
=> Adding php templates

synthtool/gcp/templates/node_library/.circleci/config.yml.j2
This fixes a bug with publishing TypeScript packages.
=> Run `npm install` before publishing

synthtool/transforms.py, tests/test_transforms.py
```python
transforms.move(
source,
destination,
excludes=['garbage.md']) # after this change, this will be relative to the source, not destination
```
So if there exists a `source/garbage.md`, it will be ignored.
Please let me know if this change makes sense to you.
=> Move: excludes arg paths should be relative to source, not destination

synthtool/gcp/templates/node_library/.circleci/config.yml
This will fix nodejs-dlp's system-test failures on master: https://circleci.com/workflow-run/9f90675e-df3b-452f-a2e9-bc1ef6f1d9bb
=> add GCLOUD_PROJECT env var to config.yml

synthtool/gcp/templates/node_library/.kokoro/system-test.sh
This allow some (non-autogenerated) repositories to have custom logic before certain tests are run.
In this case I've implemented it for system-test, but we will likely have one for each test (test.sh, samples-test.sh) depending on need.
Specifically, we need this in nodejs-storage to export 2 additional environment variables (the second project/service account).
=> node: add a pretest hook on system test

synthtool/gcp/templates/node_library/.kokoro/system-test.sh
This is currently causing nodejs-dlp's system-test to [fail](https://source.cloud.google.com/results/invocations/05366cda-3997-406f-a744-a6aea902682e/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fgoogleapis%2Fnodejs-dlp%2Fcontinuous%2Fnode8%2Fsystem-test/log).
=> nodejs: export GCLOUD_PROJECT in system-test

setup.py, synthtool/__main__.py, synthtool/main.py
See #32 
```
busunkim-macbookpro1:automl busunkim$ synthtool --version
0.8.0
busunkim-macbookpro1:automl busunkim$ synthtool
synthtool > Executing /Users/busunkim/GCP/google-cloud-python/automl/synth.py.
synthtool > Ensuring dependencies.
synthtool > Pulling artman image.
synthtool > Cloning googleapis.
```
=> Make synthtool an executable

synthtool/gcp/templates/node_library/.kokoro/samples-test.sh
We are already adopting this pattern on system-tests and now we want to set up some environment variables before samples tests are run for DLP.
=> feat(node): allow pre-samples-test.sh hook

synthtool/gcp/__init__.py, synthtool/gcp/artman.py, synthtool/gcp/discogapic_generator.py, synthtool/gcp/gapic_generator.py
Java Compute uses a discogapic generator (the a gapic generator that accepts discovery docs rather than protos). This adds a new generator that fetches the discovery-artifact-manager repo.
The java compute synth would end up like:
```python3
import synthtool as s
import synthtool.gcp as gcp
gapic = gcp.DiscoGAPICGenerator()
common_templates = gcp.CommonTemplates()
library = gapic.java_library(
service='compute',
version='v1',
config_path='artman_compute.yaml',
artman_output_name='')
s.copy(library / 'gapic-google-cloud-compute-v1/src', 'src')
```
=> Add discogapic generator

.kokoro/build.sh
The correct nox is now installed in the python docker image.
=> Remove nox-automation uninstall from build.sh

synthtool/gcp/gapic_generator.py
=> Add option to specify local googleapis directory

synthtool/gcp/templates/node_library/.kokoro/presubmit/windows/common.cfg
We are not dumping test results to `sponge.xml` and it was causing issues when Kokoro tries to pull it from the VM.
=> fix(node): remove define_artifacts from Node.js's Windows kokoro build

synthtool/gcp/templates/node_library/.circleci/config.yml
I need `npm link` in system tests for gax. It does not change any behavior for other libraries.
Context: https://github.com/googleapis/gax-nodejs/pull/334
=> fix: make npm link work for system tests

synthtool/gcp/artman.py, synthtool/shell.py
Closes #118. 
I wasn't sure whether to show `stdout` for _only_ docker pull or every time the `run` function is called.
=> Show stdout for docker pull

CHANGELOG.md, setup.py
=> Release synthtool 2018.11.08

.coveragerc, noxfile.py, synthtool/__main__.py, synthtool/metadata.py, synthtool/sources/git.py, tests/test_git.py, tests/test_metadata.py
Sorry for the large changeset here. I wanted to leave things better than I found them, so I ended up writing tests for the `git` module.
=> Add metadata reporting for Git sources.

synthtool/__main__.py, synthtool/gcp/gapic_generator.py
This has two benefits:
1. speeds things up a bit if googleapis-private isn't used.
2. makes the metadata file only contain googleapis-private if it's actually used.
=> Lazily clone googleapis{-private}

synthtool/gcp/common.py, synthtool/gcp/templates/python_library/.flake8, synthtool/gcp/templates/python_library/MANIFEST.in, synthtool/gcp/templates/python_library/setup.cfg
See #94 
* The .flake8 files look like the template here, with the exception of [api_core](https://github.com/googleapis/google-cloud-python/blob/0e2c54ce54909467b202a73f04fc3aa4a29a749b/api_core/.flake8) and [core](https://github.com/googleapis/google-cloud-python/blob/0e2c54ce54909467b202a73f04fc3aa4a29a749b/core/.flake8).
* The _majority_ of `MANIFEST.in` files look like the template. These are the exceptions.
* [api_core/MANIFEST.in](https://github.com/googleapis/google-cloud-python/blob/0e2c54ce54909467b202a73f04fc3aa4a29a749b/api_core/MANIFEST.in)
* [core/MANIFEST.in](https://github.com/googleapis/google-cloud-python/blob/0e2c54ce54909467b202a73f04fc3aa4a29a749b/core/MANIFEST.in)
* [bigquery/MANIFEST.in](https://github.com/googleapis/google-cloud-python/blob/0e2c54ce54909467b202a73f0 …
=> Add initial python templates

synthtool/__main__.py, synthtool/metadata.py
Closes #137 (or at least makes it possible to fix it)
=> Add option to change metadata output location

synthtool/__init__.py
Towards #130.
We can't outright disable this yet, as autosynth uses the direct execution method and the elixir and java apiary client expect to have access to `sys.argv`.
=> Warn when running the synthesis script directly

synthtool/languages/java.py
Usage would be something like:
```python
import synthtool.languages.java as java
java.format_code("./src")
```
Note the gapic-generator does run version 1.1 of the Google java formatter and this one defaults to 1.6 (most up to date). We can update the one in gapic, but we'd also like the ability to run this on our apiary libraries too.
=> Add ability to format java code with a custom google-java-format version

synthtool/gcp/templates/python_library/.coveragerc, synthtool/gcp/templates/python_library/.flake8, synthtool/gcp/templates/python_library/noxfile.py.j2
Copy black flake8 ignore elements to not conflict with black formatting. 
A good number of our libraries require core as part of their tests. Add this to localdep in noxfile.
=> Update python templates

synthtool/gcp/gapic_generator.py, synthtool/metadata.py, synthtool/protos/metadata.proto, synthtool/protos/metadata_pb2.py, tests/test_metadata.py
Metadata now looks like this:
```
{
"sources": [
{
"generator": {
"name": "artman",
"version": "0.16.2",
"dockerImage": "googleapis/artman@sha256:2f6b261ee7fe1aedf238991c93a20b3820de37a343d0cacf3e3e9555c2aaf2ea"
}
},
{
"template": {
"name": "python_library",
"origin": "synthtool.gcp",
"version": "2018.11.28"
}
},
{
"git": {
"name": "googleapis",
"remote": "https://github.com/googleapis/googleapis.git",
"sha": "58249308b9c7bd64ba18ce99100751397e5184a7",
"internalRef": "223077517"
}
}
],
"destinations": [
{
"client": {
"source": "googleapis",
"apiName": "vision",
"apiVersion": "v1",
"language": "python",
"generator": "gapic",
"config": "google/cloud/vision/artman_vision_v1.yaml"
}
}
]
}
```
=> Report gapic generation to metadata

synthtool/gcp/templates/node_library/.circleci/config.yml
Openssl got upgraded (probably to v1.1.0) in the Docker image used by CircleCI, and it now changed the default algorithm used for decryption, which made all our encrypted keys incompatible. Adding the `-md md5` to `openssl -d` (following [this advice](https://wiki.archlinux.org/index.php/OpenSSL#%22bad_decrypt%22_while_decrypting)) helps ([example workflow](https://circleci.com/workflow-run/2ed13275-1ecf-476d-8644-2435e6394c8b)).
=> fix: pass -md option to openssl

synthtool/languages/java.py
The java formatter is rules based and the output from the first pass is
not guarantee to pass linting yet. For example, if unused imports are
removed, it may not clean up double line break whitespace.
=> Run the java formatter more than once.

synthtool/__main__.py
Closes #143
These can be accessed via:
```
from __main__ import extra_args
print(extra_args())
```
or
```
from synthtool.__main__ import extra_args
print(extra_args())
```
=> Allow access to additional arguments passed to synthtool

synthtool/gcp/discogapic_generator.py, synthtool/gcp/gapic_generator.py
This option will enable requesting the protos files to be in genfiles.
=> Add include_protos option to generation

README.md
Per https://github.com/googleapis/synthtool/blob/8e95a2333f4c5fc5e12a319b33664d75b06ae620/synthtool/gcp/gapic_generator.py#L27 the environment variable is `SYNTHTOOL_GOOGLEAPIS`.
I get a warning when I run `python synth.py`.
=> Update readme to latest instructions

synthtool/languages/java.py
Our presubmit code format build has been upgraded to 1.7. We'll need to upgrade here as well to prevent conflicts with our generated autosynth PRs.
For reference: https://github.com/googleapis/google-cloud-java/issues/4438
As this is my first PR in this codebase, please let me know if there are any additional changes required. Thanks!
=> Update java formatting version to 1.7

synthtool/gcp/templates/node_library/.kokoro/release/publish.cfg
Releasetool reporter will go through the magic github proxy to make requests to the GitHub API.
=> node(kokoro): Fetch credentials for magic github proxy

synthtool/gcp/common.py, synthtool/gcp/templates/node_library/README.md, synthtool/languages/node.py, synthtool/sources/templates.py, tests/fixtures/samples/quickstart.js, tests/test_templates.py
I'm midway through porting over the logic from `nodejs-repo-tools` for generating `samples/README.md`, and `./README.md`.
This process was made easier by the fact that @busunkim96 has been working to define a better meta-information file for our repos, which looks like this:
```json
{
"name": "storage",
"name_pretty": "Google Cloud Storage",
"product_documentation": "https://cloud.google.com/storage", 
"client_documentation": "https://cloud.google.com/nodejs/docs/reference/storage/2.3.x/",
"issue_tracker": "https://issuetracker.google.com/savedsearches/559782",
"release_level": "ga",
"language": "nodejs",
"repo": "googleapis/nodejs-storage",
"distribution_name": "@google-cloud/storage"
}
```
☝️ prior to this effort, there was a standard way to fetch a lot of this information.
=> feat: porting README generation from nodejs-repo-tools

setup.py, synthtool/gcp/common.py, synthtool/gcp/templates/node_library/README.md, tests/fixtures/.readme-partials.yml, tests/test_templates.py
based on conversation in https://github.com/googleapis/nodejs-storage/pull/645, introduces support for `.readme-partials.yml -- I think this is quite valuable, in that it will give us more flexibility to gradually iterate on the structure of content on a repo by repo basis, while still automating the bits that can be automated, e.g., samples.
=> feat: add support for README partials

synthtool/gcp/common.py, synthtool/sources/templates.py
This would protected us from the wall of broken README PRs we got last night.
We will want to do the same with `samples/README.md` generation.
=> feat: skip README rendering if .repo-metadata.json does not exist

synthtool/gcp/common.py, synthtool/gcp/templates/node_library/README.md, synthtool/gcp/templates/node_library/samples/README.md, synthtool/sources/templates.py, tests/test_templates.py
similar to the work with `./README.md`, `synthtool` will now regenerate `samples/README.md` as changes are made to the samples directory.
=> feat: also generate samples/README.md

synthtool/__main__.py, synthtool/gcp/common.py, tests/test_common.py
The simple algorithm I wrote for decamelize did not support acronyms well (the bug is [seen here](https://github.com/googleapis/nodejs-bigquery/blob/45b6f7634e6517ca217c0d73b59b818256549750/README.md)).
This PR extends the method adding this functionality and adds tests for this edge-case; CC: @steffnay
fixes: #219
=> fix: support consecutive capital letters

synthtool/gcp/artman.py, synthtool/gcp/gapic_generator.py, synthtool/protos/metadata_pb2.py
This enables the possibility of sample generation via the `--dev_samples`
option to the gapic generator. Tested with the Data Catalog Python
client via
```
library = gapic.py_library(
"bigquery_datatransfer",
version,
config_path="/google/cloud/bigquery/datatransfer/"
"artman_bigquerydatatransfer.yaml",
artman_output_name="bigquerydatatransfer-v1",
include_protos=True,
generator_args=["--dev_samples"],
)
```
Closes #223
=> feat: Add `generator_args` arg to populate `--generator-args` artman option

synthtool/gcp/templates/node_library/samples/README.md
The value `None` was printing in `samples/README` if no `.readme-partials.yaml` was provided ([see](https://github.com/googleapis/nodejs-bigquery/blob/5827be263eea9b97871918fcfca92243ce18465a/samples/README.md)).
CC: @steffnay this will address a little blip I saw in your auto generated README; I wouldn't let it block you, as READMEs will be generated automatically nightly.
=> fix: None was printing in samples/README if introduction missing

synthtool/gcp/common.py, synthtool/gcp/templates/ruby_library/AUTHENTICATION.md, tests/test_templates.py
Add `AUTHENTICATION.md` for all GAPIC packages in googleapis/google-cloud-ruby.
[refs googleapis/google-cloud-ruby#2933]
Example usage in a google-cloud-ruby package:
```sh
diff --git a/google-cloud-bigquery-data_transfer/synth.py b/google-cloud-bigquery-data_transfer/synth.py
index 15fd8f222..3f1df1cd9 100644
--- a/google-cloud-bigquery-data_transfer/synth.py
+++ b/google-cloud-bigquery-data_transfer/synth.py
@@ -38,6 +38,17 @@ s.copy(v1_library / '.gitignore')
s.copy(v1_library / '.yardopts')
s.copy(v1_library / 'google-cloud-bigquery-data_transfer.gemspec', merge=ruby.merge_gemspec)
+# Copy common templates
+common_templates = gcp.CommonTemplates()
+metadata = {
+    "package_name": "google-cloud-bigquery-data_transfer",
+    "module_name": "Bigquery::DataTransfer",
+ …
```
=> ruby: add AUTHENTICATION.md template

synthtool/gcp/templates/python_library/noxfile.py.j2
The package needs to be installed in the session before the docs to be built.
=> Update noxfile.py template.

synthtool/gcp/common.py, synthtool/gcp/templates/node_library/README.md, synthtool/gcp/templates/node_library/samples/README.md
This adds the feature everyone's been asking for ...
_The ability to override the default title in a README using *.readme-partials.yaml*._
Note that it assumes that you will provide the full title as markdown, including the heading type, so so something like:
```
```
see: https://github.com/googleapis/nodejs-firestore-session/pull/6
=> feat: provide 'title' in .readme-partials.yaml to override the default

synthtool/transforms.py, tests/test_transforms.py
#48 introduced a bug where the exclude path (which is relative to a tracked path) is compared to a source path (which is relative to the source root).
This issue was unnoticed because it works ok when the source path has a single component like in firestore:
https://github.com/googleapis/nodejs-firestore/blob/89afae/synth.py#L19
But breaks when the source path has multiple components like in bigtable:
https://github.com/googleapis/google-cloud-java/blob/264643/google-cloud-clients/google-cloud-bigtable/synth.py#L30
And when the cwd doesn't match the tracked path
=> Fix move excludes

synthtool/gcp/templates/node_library/.kokoro/lint.sh, synthtool/gcp/templates/node_library/.kokoro/samples-test.sh, synthtool/gcp/templates/node_library/.kokoro/test.sh
1. in `lint.sh` only `npm install` in samples directory if a `samples/package.json` exists.
1. in `samples-test.sh` only run samples tests if a `samples/package.json` exists.
1. ini `test.sh` only pipe coverage to `codecov` if on Node 10, don't try to run `nyc` if it doesn't exist (allowing us to opt for `c8` in some cases).
=> build: build script tweaks for non-standard libraries

synthtool/gcp/templates/node_library/.kokoro/test.bat
this `test.bat` file will unblock our broken Windows builds, it's pretty hacky; let me explain:
1. the image we shipped has an ancient version nvm, which installs Node@10.15.3 successfully, but fails to install npm (this might be because npm was moved from npm/npm to npm/cli).
2. the 8.9.1 version of Node.js has npm working \o/ hooray; so we can just use this to install the latest npm in 10.15.3 -- wrong!
3. the version of npm that installs with 8.9.1 apparently can't be run by Node 10 ... go figure.
tldr; the fix uses v8.9.1 to install the latest npm, then switches to 10.15.3 and uses this npm to install the latest version of npm on 10.15.3 (I think the second install is the easiest way to get all the linking correct).
=> fix: temporary fix for broken Windows image

synthtool/gcp/templates/node_library/.kokoro/continuous/node10/test.cfg, synthtool/gcp/templates/node_library/.kokoro/continuous/node8/test.cfg
once we roll out Node 12, we should switch from 10 to 12.
=> fix: move codecov token to node10

README.md
- Add usage for Node.js, Java, PHP, and Ruby
- Add useful links throughout README
- Syntax highlight Python code demonstrating synth.py features
- Document include_protos=True
- Document CommonTemplates including Jinga basics and reference links
- Little bits of consistency, e.g.
- no newline after header
- new newlines around code blocks
- SynthTool when referring to tool/product
- `synthtool` when explicitly referring to the CLI
- Python is always used as the primary language. All languages which support SynthTool are included and always included in alphabetical order (with Python always starting first).
=> README updates (various)

synthtool/gcp/templates/node_library/.kokoro/continuous/node10/common.cfg, synthtool/gcp/templates/node_library/.kokoro/presubmit/node10/common.cfg, synthtool/gcp/templates/node_library/.kokoro/presubmit/node10/test.cfg, synthtool/gcp/templates/node_library/.kokoro/samples-test.sh, synthtool/gcp/templates/node_library/.kokoro/system-test.sh, synthtool/gcp/templates/node_library/.kokoro/test.sh
codecov collects coverage across all test environments, demonstrated here:
https://codecov.io/gh/googleapis/release-please (all the github tests are integration, and are combined with the other unit tests).
I would like to pipe coverage in our samples and system tests, to give better insight into our coverage, regardless of the types of tests folks write.
=> build: collect coverage across additional test environments

synthtool/gcp/common.py, synthtool/gcp/templates/node_library/samples/README.md
adds support for `samples_body` to allow for the customization of the body of `samples/README.md`.
see: https://github.com/googleapis/nodejs-translate/pull/268
CC: @beccasaurus.
=> feat: add support for samples_body partial in samples/README.md

README.md
In [google-cloud-python](https://github.com/googleapis/google-cloud-python), we do not use the `google-cloud-` prefix in the directory for each individual API.
=> [docs] Fix a small README error.

synthtool/gcp/templates/node_library/.nycrc
This should undo the revert in https://github.com/googleapis/nodejs-firestore/commit/62eaab0dd6d2a0f6d06880d171f6862194833aef#diff-774bc7673169ae00d4c2bd961ab79828 and bring the `@google-cloud/firestore` coverage up from 62% to 96%.
=> fix: Ignore "protos" directory for Node coverage

synthtool/gcp/templates/node_library/.kokoro/docs.sh, synthtool/gcp/templates/node_library/.kokoro/lint.sh, synthtool/gcp/templates/node_library/.kokoro/samples-test.sh, synthtool/gcp/templates/node_library/.kokoro/system-test.sh, synthtool/gcp/templates/node_library/.kokoro/test.sh, synthtool/gcp/templates/node_library/.kokoro/trampoline.sh
several of our shell jobs were configured to output verbose information, including environment variables; this is risky in a CI/CD environment (as we're potentially passing secrets into jobs).
=> fix: shell jobs were outputting too much information

synthtool/gcp/common.py
I found an edge-case in which a suffix can exist for a quickstart region tag can have a suffix, this addresses that edge-case so that we can avoid changing the region tag and still generate our standard README.
=> fix: some quickstart region tags include suffix

synthtool/gcp/templates/python_library/noxfile.py.j2
=> Suppress checking 'cov-fail-under' in default session.

synthtool/gcp/templates/python_library/noxfile.py.j2
Run samples much like you would system tests. Use
`samples/requirements.txt` to add samples-only dependencies.
=> Add samples session to noxfile, controlled by `samples_test` arg.

README.md, synthtool/gcp/artman.py, synthtool/gcp/gapic_generator.py
```
export SYNTHTOOL_GENERATOR=/path/to/gapic-generator
```
Fixes #250 
**See update to README below for description :)**
---
Refresher on how this is used:
- I work on and with the monolithic generator.
- Today, SynthTool runs artman which includes the latest version of gapic-generator (in the image)
- Today, the easiest way for me to run SynthTool with changes to gapic-generator is to push a new version of artman, without much local testing
- With this, I/we can run SynthTool locally while developing gapic-generator and verify functionality much easier! Very helpful :)
Considerations:
- While today there is one "generator", that will not always be the case.
- But the current codebase is authored based around artman which is based around the single generator use-case.
- As such, I am not …
=> Add support for using local GAPIC generator

synthtool/gcp/templates/node_library/.jsdoc.js, synthtool/gcp/templates/node_library/README.md
Adds an anchor, so that when linking out to `googleapis.dev`, we can link directly to the section of the page that has reference docs.
=> feat: add anchor so that we can link directly to reference docs

synthtool/gcp/templates/python_library/noxfile.py.j2
Due to concerns that black updates could randomize our automated generations, I am pinning black to its latest release.
=> Pin black to avoid automated synth updates.

synthtool/gcp/gapic_generator.py
It appears synthtool will raise a `FileNotFoundError` when `gen-manifest` isn't available.
See https://github.com/googleapis/google-cloud-python/issues/9181
CC @beccasaurus
=> Catch FileNotFoundError for gen-manifest

synthtool/gcp/templates/node_library/.eslintignore
We've got some generated stuff in `protos/`, such as `protos.js` and `protos.d.ts`, they are huge and we don't want `eslint` to check/fix them.
=> fix: do not eslint in protos/

synthtool/gcp/templates/node_library/.github/PULL_REQUEST_TEMPLATE.md
In most nodejs libraries we have a pull request template, but it wasn't part of our common files (ooops).  This proposes a common template.  If we like this, we would expand it out to other languages as well.
=> fix(node): add a common pull request template

synthtool/gcp/templates/node_library/.github/PULL_REQUEST_TEMPLATE.md
A couple small tweaks:
1. we now go directly to opening an issue for the user.
2. we now use `repo` rather than `name`, as the two can vary.
=> fix: use repo rather than name

synthtool/gcp/templates/node_library/CONTRIBUTING.md
Porting further upstream into the origin of the CONTRIBUTING docs ([original](https://github.com/googleapis/nodejs-firestore/pull/772))
=> docs: update contributing docs to include running tests

synthtool/gcp/templates/java_library/renovate.json
In most places, we import guava-bom rather than directly using guava, but still allow guava packages to be updated.
=> fix: relax guava package name

synthtool/gcp/templates/java_library/.github/ISSUE_TEMPLATE/bug_report.md
The template synthtool/gcp/templates/java_library/.github/ISSUE_TEMPLATE/bug_report.md was incorrectly using `name` to
generate the github URL which would result in getting:
```
https://github.com/googleapis/conformance-tests
```
instead of
```
https://github.com/googleapis/java-conformance-tests
```
=> bug: update bug_report.md template to use `repo_short`

synthtool/gcp/templates/java_library/.kokoro/release/snapshot.sh
This will prevent extra staged deployments of versions in case master is not on a SNAPSHOT build
=> fix(java): skip snapshot unless a snapshot is detected

synthtool/languages/java.py
This will greatly simplify our synth.py scripts across our split java repos. We do all of these steps when we generate a java versioned library.
=> feat: add helper for the most common Java library synth generation

synthtool/gcp/templates/java_library/.kokoro/build.sh, synthtool/gcp/templates/java_library/.kokoro/coerce_logs.sh, synthtool/gcp/templates/java_library/.kokoro/continuous/common.cfg, synthtool/gcp/templates/java_library/.kokoro/nightly/common.cfg, synthtool/gcp/templates/java_library/.kokoro/presubmit/common.cfg
Currently, sponge thinks our junit tests are flaky because there are multiple `sponge_log.xml` log files (jUnit XML format) in the same output directory. This adds a post-processing script to move them to separate directories. In the ResultsStore UI, these will be found and separate targets, as well as in sponge.
=> feat(java): process sponge logs after tests

synthtool/gcp/templates/java_library/.kokoro/build.sh, synthtool/gcp/templates/java_library/.kokoro/presubmit/clirr.cfg
Currently, all presubmits fail if the maven-clirr-plugin fails. This causes lots of noise trying to determine what actually fails. clirr check happens on `verify` which happens as part of `install`.
Locally,  a user will still see the run clirr when running install, but in CI, we will split it out into a separate job. To do so, we skip clirr on install, units, and integration tests and create a new job type for clirr.
=> feat(java): split clirr check into separate kokoro job

synthtool/gcp/gapic_generator.py, synthtool/languages/java.py
Java has a special, deep directory structure for generated samples. Therefore, we need to make the directory structure configurable for` _include_samples()`.
=> feat(java): enable samplegen

synthtool/gcp/templates/ruby_library/AUTHENTICATION.md
Update the list of GCP environments in the Ruby library `AUTHENTICATION.md` template to include Google Cloud Functions (GCF) and Cloud Run. Remove incomplete and outdated list of example scopes.
refs: googleapis/google-cloud-ruby#3696
=> docs(ruby): update the list of GCP environments in AUTHENTICATION.md

synthtool/gcp/templates/node_library/.nycrc
excluding ` "**/src/**/v*/**/*.js"` prevents us from getting interesting insights into how our libraries are tested. As an example, I just ran `@google-cloud/translate` with this stanza removed, and it told me we don't call `getProjectId` in our unit tests:
I think we should cover `src` by default, and if there's a compelling reason to remove it for some projects we can exclude `.nycrc` in `synth.py`.
=> feat(coverage): start providing coverage for src

synthtool/gcp/gapic_microgenerator.py
Now it says: 
```
synthtool > Pulling Docker image: gapic-generator-{language}:{generator_version}
```
Marking the string as `f"  "` to make the placeholders work.
=> fix: formatted log message

synthtool/gcp/gapic_microgenerator.py
Sometimes we'll need to pass some extra proto files, such as `google/cloud/common_resources.proto`, to microgenerators. The idea is to mount all the extra files into the Docker image (e.g. `/extra/google/cloud/common_resources.proto`), and pass all of them as options (passing `-I /extra` for `protoc`, and then all the filenames).
=> feat: pass extra protos to a microgenerator

synthtool/gcp/templates/python_library/docs/_static/custom.css, synthtool/gcp/templates/python_library/docs/_templates/layout.html
The wording has been changed slightly since I took this screenshot, but the formatting is the same.
The banner will not appear until there is a small change to docs/conf.py in https://github.com/googleapis/gapic-generator/pull/3020
=> docs(python): add Python 2 sunset banner

synthtool/gcp/templates/java_library/.github/release-please.yml
This causes breaking changes in pre-1.0 Java libraries to be bumped with minor versioning rather than to 1.0.0
=> fix(java): set bumpMinorPreMajor for Java releases

synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
This prevents both the clirr and dependencies check from failing when the clirr check fails.
=> fix(java): skip clirr check in the dependencies presubmit check

synthtool/gcp/common.py
see: https://github.com/googleapis/nodejs-logging/pull/650
=> fix: we should allow for files with dashes in samples folder

synthtool/gcp/templates/node_library/renovate.json
we're opting to pin TypeScript for the time being, until such time as we can figure out a better resolution for tickets like https://github.com/googleapis/google-auth-library-nodejs/issues/844.
_Note: this should not land until we've run automated tooling across all our repos to update configuration._
=> chore: pin TypeScript for the time being

synthtool/gcp/gapic_microgenerator.py
Recent `synthtool` runs with micro generator has failed with
```
synthtool > Failed executing docker run --mount type=bind,source=/home/kbuilder/.cache/synthtool/googleapis/google/devtools/cloudbuild/v1/,destination=/in/google/devtools/cloudbuild/v1/,readonly --mount type=bind,source=/tmpfs/tmp/tmp3qua4out/,destination=/out/ --rm --user kbuilder gcr.io/gapic-images/gapic-generator-typescript:latest --grpc-service-config google/devtools/cloudbuild/v1/cloudbuild_grpc_service_config.json:
docker: Error response from daemon: linux spec user: unable to find user kbuilder: no matching entries in passwd file.
```
It can be easily fixed by passing an ID of the current user instead of its name. To stay compatible (e.g. if anyone wants to run it on Windows), fallback to the current scenario if …
=> fix: pass user id to docker run if possible

synthtool/gcp/templates/java_library/renovate.json
Common build plugin updates should now send PRs and `build(deps): [message]`, other updates should use `deps: [message]`.
Fixes guava's version scheme to preserve the guava flavor (`-android` vs `-jre`).
Note that the other groups all should be importing their boms (grpc, gax), and OpenCensus is on its last version and are all up to date already.
Sample PRs: https://github.com/chingor13/renovate-test/pulls
=> fix(java_templates): fix renovate configuration

synthtool/gcp/templates/node_library/.nycrc
These files are not executable, so their coverage will always be 0.
This increases coverage in Firestore by 8% (https://github.com/googleapis/nodejs-firestore/pull/852)
=> build: exclude .d.ts files from coverage

synthtool/gcp/templates/java_library/.kokoro/build.sh, synthtool/gcp/templates/java_library/.kokoro/continuous/samples.cfg, synthtool/gcp/templates/java_library/.kokoro/nightly/samples.cfg, synthtool/gcp/templates/java_library/.kokoro/presubmit/samples.cfg, synthtool/gcp/templates/java_library/CONTRIBUTING.md
In `com.google.cloud:google-cloud-shared-config:0.3.1` integration tests
are skipped by default to reduce friction from contributors that do not
have a service account or access to GCP services. This change updates
our templates to provide instructions on how to enable integration tests
as well as passing the necessary arguments to our builds.
With the incorporation of Code Samples into the project repos we need
new configuration and control in maven to allow building on jdk7 and
excluding samples from release deploy builds. This change adds new build
configs for samples and a new target to build.sh to build samples.
=> feat(java_template): add support for enable-integration-tests and enable-samples maven profiles

synthtool/languages/java.py
Some of the new clients do not use the artman docker image and instead use bazel. For these libraries, we can share common behavior between the artman generation and the bazel generator for things like code formatting and fixing license headers.
This PR pulls the shared code of copying to the correct destination folder into a private `_common_generation()` function which is shared between the `java.gapic_library()` and `java.bazel_library()` functions.
Fixes: https://github.com/googleapis/java-secretmanager/issues/11
=> feat(java): add helper for bazel generation

synthtool/gcp/templates/java_library/renovate.json
This allows renovate to bump version like 0.1.2-beta to 0.2.0-beta
=> fix(java_template): allow renovate to update 'unstable' deps

synthtool/metadata.py
Didn't observe any misbehavior, but this is more correct.
=> fix: use the locale's encoding for interprocess pipes

noxfile.py, synthtool/languages/java.py, tests/test_language_java.py
As we move to templatize our java README files, we will need the ability to fetch the latest version of Maven artifacts from Maven Central.
This PR adds the ability to fetch and parse the latest version from Maven Central.
=> feat(java): add helper for fetching the latest version of a Maven artifact

synthtool/languages/java.py
Some services (e.g. BigQuery Storage) have a different destination folder structure for historical reasons (bigquerystorage vs bigquery-storage). This PR allows you to override the output folder.
This was necessary to generate BigQuery Storage's v1beta2 client: https://github.com/googleapis/java-bigquerystorage/pull/44
=> feat(java): allow overriding the destination service folder name

synthtool/metadata.py, tests/test_metadata.py
Fixes https://github.com/googleapis/synthtool/issues/390
The file system's timestamps are not reliable; there is no way synth.py should have ever ended up in the list of generated files, as happened here: https://github.com/googleapis/nodejs-datalabeling/blob/95d32ddc0b8389dc28ca47951da7019fe3451e0d/synth.metadata#L367
=> fix: turn off obsolete file tracking by default

synthtool/gcp/templates/java_library/renovate.json
Guava usually needs to be bumped alongside many other dependencies. Without group them, the individual PRs will fail dependency upper bounds checks
Example of grouped PR: https://github.com/googleapis/java-webrisk/pull/46
=> fix(java_templates): group guava with other core dependencies

synthtool/gcp/templates/python_split_library/noxfile.py.j2
This directory exists in the mono-repo but won't exist by default in the split repositories.
https://github.com/googleapis/google-cloud-python/tree/master/test_utils
=> chore(python): don't install test_utils

synthtool/gcp/templates/java_library/.kokoro/linkage-monitor.sh
Update the linkage-monitor script to skip clirr and enforcer which are run by separate checks.
Currently, the linkage monitor check also fails when clirr fails or upper bounds dependencies checks fail which is a false signal.
=> fix(java_templates): skip clirr, enforcer in linkage monitor

noxfile.py
`generate_protos` should run before `blacken` so the pb2 file keeps its formatting
=> chore: run generate_protos session before blacken

synthtool/gcp/templates/python_split_library/noxfile.py.j2
The change I proposed isn't universally going to work, where google.cloud will. removing.
This change, while it will work for some libraries, others will report zero data to check for coverage.
=> fix: revert coverage path change

synthtool/gcp/common.py
Some of our Node.js repos started failing due to "repo" no longer being defaulted to an empty object, see: https://github.com/googleapis/gaxios/issues/231.
Would it be alright if we continue populating an empty object for the time being?
=> fix: exception occurring due to missing "repo" field

setup.py, synthtool/metadata.py, synthtool/protos/metadata.proto, synthtool/protos/metadata_pb2.py, tests/test_metadata.py
In the wild, the file system's timestamps can't be trusted.  Perhaps there are unknown processes opening the files for write.  So the strategy of checking file timestamps to see what has changed won't work.
=> refactor: remove code that tracks obsolete files

synthtool/gcp/common.py
`kwargs["metadata"]["samples"]` errors if there are no samples in `kwargs["metadata"]`
```
File "/usr/local/google/home/busunkim/.local/lib/python3.6/site-packages/synthtool/gcp/common.py", line 43, in _generic_library
if not kwargs["metadata"]["samples"]:
KeyError: 'samples'
```
=> fix: check if "samples" not in kwargs["metadata"]

synthtool/metadata.py, tests/test_metadata.py
The working repo may contain a github user token in the URL, so
recording it could leak the token.
=> fix: do not record the working repo in the metadata

synthtool/log.py
When the output of synthtool was logged to a file, it contained ansi color switching codes, which look like garbage.
=> fix: only write color codes to a tty

synthtool/languages/java.py, synthtool/transforms.py, tests/test_transforms.py
If you set the `required=True` option, synthtool will now raise a `MissingSourceError` and fail your synth run.
If the output of the generator changes for whatever reason, we can silently miss the fact that no files were copied as the default behavior is to warn a message. We may miss this if autosynth does not fail its synth run and notify us.
=> feat: add required option to s.copy()

synthtool/gcp/templates/node_library/.github/workflows/ci.yaml, synthtool/gcp/templates/node_library/.kokoro/samples-test.sh, synthtool/gcp/templates/node_library/.kokoro/system-test.sh, synthtool/gcp/templates/node_library/.kokoro/test.sh, synthtool/gcp/templates/node_library/.mocharc.js
This PR cleans up our Node.js test configuration a bit:
1. adding support for build-cop, so that we can start getting more diligent about tracking down flaky tests.
2. fixing coverage, which was broken when we moved to GitHub actions (the script we used didn't have a way to get a per repository token, and was silently failing).
=> build(nodejs-tests): adds support for build-cop and fixes coverage

synthtool/languages/java.py
No longer necessary to provide the `package_pattern` for the gRPC header.
This will allow us to simplify the `synth.py` files in the repository.
=> fix(java): relax regex for grpc header fix

tests/fixtures/java_templates/standard/.repo-metadata.json, tests/test_language_java.py
Towards #436 
This tests if `java.common_templates()` succeeds and will allow us to extend this for testing the output of the generated templates.
For this, we copy the fixture to a temporary directory and run the common templates helper from that directory.
=> test: add test for generating common java templates

synthtool/gcp/templates/java_library/.github/trusted-contribution.yml
This is to not overwhelm Kokoro CI on every commit to master (reopens the release PR and re-run CI). With merge-on-green, having the CI pre-run is not a huge concern.
Most java repositories already have this configuration set.
=> fix(java): set only renovate-bot as a trusted contributor

README.md, synthtool/gcp/common.py
Clone a copy of the templates repo (currently synthtool) for template
generation. This will support the use case of precloning and walking
through the commit history for context-aware-commits and for possibly
extracting templates to a separate repository.
You can also supply a `SYNTHTOOL_TEMPLATES` environment variable
to provide a local directory which contains templates similar to how we
treat googleapis/googleapis for protos.
=> feat: track templates as git clone

synthtool/gcp/common.py
I was getting an exception when setting the `SYNTHTOOL_TEMPLATES` environment variable.
=> fix: joining / fails for string type

synthtool/gcp/snippets.py, tests/test_snippets.py
When parsing snippets from the source file, trim leading spaces while maintaining extra indentation. This implementation finds the minimum indentation, ignoring empty lines and removes that many spaces from each line.
=> fix(snippets): trim leading whitespace when extracting snippets

synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
This pulls in checkout@v2 so we can avoid the bug listed below:
https://github.com/actions/checkout/issues/23
It does work with v1, but manually re-running tests will fail with a weird checkout failure. Subsequent pushes may also not properly re-run.
=> build: use checkout@v2, not v1, as this allows manual re-running of tests

synthtool/gcp/templates/node_library/README.md
Document our version support goals on all repos, the goal being to unblock folks who accidentally install a Node 10 version of a library in a Node 8 runtime.
_I would like to create a mass PR for this change manually, before merging, so that we don't end up with 85 PRs we need to change in the morning._
=> docs: document the release schedule we follow

synthtool/gcp/templates/java_library/.kokoro/build.sh, synthtool/gcp/templates/java_library/.kokoro/common.sh, synthtool/gcp/templates/java_library/.kokoro/dependencies.sh, synthtool/gcp/templates/java_library/.kokoro/linkage-monitor.sh
This will retry the `mvn install` command up to 3 times with 10, 20, 40 sleep in between attempts.
This is to reduce the flakiness of the `mvn install` command when we have difficulties downloading dependencies from Maven Central. This may cause our tests to run longer if there is a compilation or enforcer error (also run by `mvn install`), but I cannot run only `mvn dependency:go-offline` as some modules depend on other modules from this repo that must be installed.
=> fix(java): run mvn install with retry

synthtool/gcp/templates/java_library/renovate.json, synthtool/languages/java.py
With the samples/install-without-bom/pom.xml referencing the latest released library, we want to mark updates of this version as a chore for renovate bot.
=> chore(java_templates): mark version bumps of current library as a chore

synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
@bcoe I think it might be a good time to update this template. Otherwise `synthtool` reverts this change back for repos where we removed node8 from the testing matrix manually. What do you think?
=> fix: do not run node 8 CI

README.md
The package is no longer regularly released to PyPI.
=> docs: remove "install stable" instructions

synthtool/gcp/templates/ruby_library/AUTHENTICATION.md
Fixes https://github.com/googleapis/google-cloud-ruby/issues/5185
=> fix(ruby): remove dead troubleshooting link from generated auth guide

synthtool/gcp/common.py, synthtool/gcp/templates/python_library/noxfile.py.j2
Modify noxfile.py to allow local and external dependencies for
system tests to be specified.
```py
templated_files = gcp.CommonTemplates().py_library(
unit_cov_level=97, 
cov_level=99, 
system_test_local_dependencies=["test_utils"],
system_test_external_dependencies=["psutil"]
)
```
=> fix: allow local and external deps to be specified

synthtool/gcp/templates/python_library/noxfile.py.j2
The error `toctree contains reference to document changlelog that doesn't have a title: no link will be generated` occurs as of 3.0.0. Pinning to 2.x until we address the docs build issue.
Towards #470
I did this manually for python-datastore https://github.com/googleapis/python-datastore/pull/22
=> fix: pin sphinx to <3.0.0 as new version causes new error

synthtool/gcp/templates/java_library/.kokoro/common.sh
Currently, if you `set -e` in the calling bash script, the first attempt will fail the entire script.
=> build(java): fix retry_with_backoff when -e option set

synthtool/gcp/templates/java_library/README.md
Prevent release-please and synthtool from fighting over the released library version. Synthtool updates the install snippets from the samples pom.xml files so the bots fight if they are temporarily out of sync after a release.
=> chore(java): release-please only updates non maven versions in README

synthtool/metadata.py, synthtool/protos/metadata.proto, synthtool/protos/metadata_pb2.py, tests/test_metadata.py
The sha for each source is a better indication of the state of the world when the last codegen occurred. This will also help us avoid merge conflicts when splitting PRs by source (multiple PRs would be updating this field in an unmergeable way).
This PR deprecates the `update_time` field and stops writing it to the metadata file.
=> fix: stop recording update_time in synth.metadata

synthtool/gcp/templates/python_library/noxfile.py.j2
We have created a new, dedicated repository for [test_utils](https://github.com/googleapis/python-test-utils). Each client's `noxfile.py` can now be configured to `session.install(...` these dependencies from the common repo. And no need to maintain a copy of the utils in each repo.
This change adds the appropriate `session.install()` instruction to the `noxfile.py` template so all new client repos are configured to use the common repository from the outset.
Refer https://github.com/googleapis/google-cloud-python/issues/10327
=> chore: installs python test_utils from its common repo

synthtool/languages/node.py
This will remove the three most copy-pasted lines from Node.js `synth.py`. When this is merged, I will make sure the `fix` npm script across all libraries works properly with samples, and we'll switch all GAPIC Node.js `synth.py` to use this post-processing.
@SurferJeffAtGoogle No tests added. Any test for this method that I can think of will be a change detector test.
=> feat: common postprocessing for node libraries

synthtool/gcp/templates/java_library/README.md
Moving forward, new clients won't be added to the google-cloud-bom until
they are stable. Thus, we should not add the default libraries-bom
install instructions if there's no bom install snippet.
When we generate a new client, we'll skip the install-with-bom snippet in the samples directory and the README will then only have the direct installation instructions.
=> chore(java): skip bom install instructions if there's no snippet

synthtool/gcp/templates/java_library/README.md
Allows setting a `versioning` section in `.readme-partials.yaml` to override the versioning section.
=> chore(java): allow overriding the versioning section of the Java README

synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
codecov's action is now authless, so let's switch back to using it rather than rolling our own token.
=> build: use codecov's action

synthtool/gcp/common.py
multiple version needs two args: `versions` and `defualt_version`:
it should be the optional arguments, but previous code throw `keyError`
=> fix: make args optional

synthtool/gcp/templates/python_library/docs/multiprocessing.rst
This will be included in `index.rst` files. See https://github.com/googleapis/python-bigtable/pull/26/files
=> chore(python): create multiprocessing doc

synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
codecov uploads fail fairly often, and it's slowing down work.
=> build: do not fail builds on codecov.io errors

.kokoro-autosynth/build.sh
The googleapis Kokoro build uses 3.0.0
https://github.com/googleapis/googleapis/blob/e0f9d9e1f9de890db765be46f45ca8490723e3eb/.kokoro/setup.sh#L10
The README also recommends Bazel >= 2.0.0.
https://github.com/googleapis/googleapis/tree/e0f9d9e1f9de890db765be46f45ca8490723e3eb#bazel
> The recommended way to build the API client libraries is through Bazel >= 2.0.0.
cc @vam-google
=> build: use Bazel 3.0.0 for autosynth builds

.kokoro-autosynth/common.cfg, autosynth/synth.py, autosynth/synthesizer.py, tests/test_synth.py
This allows autosynth to capture individual synthtool runs' output in sponge_log.log files as they are generated. We switch from using a temporary file to using a structured location: `logs/[repo]/[source]/[index]/sponge_log.log` (e.g. `logs/googleapis/java-asset/googleapis/2/sponge_log.log`). These artifacts are uploaded but not yet made public to ResultStore.
=> chore: store autosynth synth logs as sponge_log.log for use as build artifacts

autosynth/git.py, autosynth/git_source.py, autosynth/synth.py, synthtool/sources/git.py
Use synthtool's git clone function because it caches and re-uses cloned repos.
Otherwise, for each product, we cloned all the repos again, and bazel spinned up a new server for each product, and a bazel server consumes a lot of memory.
=> fix: reduce memory consumption for monorepo autosynth

autosynth/synth.py
Fixes #536 
This causes the forking behavior to fallthrough to the single branch method, but we're not checking the correct branch and aborting if there's already a PR. Thus multiple `autosynth` branches are attempted causing a 422 when creating the GitHub pull request.
=> fix: don't crash trying to double branch when forking the toolbox

autosynth/log.py, synthtool/__init__.py, synthtool/__main__.py, synthtool/gcp/artman.py, synthtool/gcp/common.py, synthtool/gcp/discogapic_generator.py, synthtool/gcp/gapic_bazel.py, synthtool/gcp/gapic_generator.py, synthtool/gcp/gapic_microgenerator.py, synthtool/languages/java.py, synthtool/languages/node.py, synthtool/log.py, synthtool/metadata.py, synthtool/shell.py, synthtool/sources/git.py, synthtool/transforms.py
When switching autosynth to use synthtool's git module, we transitively
load synthtool's logger setup which adds a log handler globally. This
causes logs to be emitted twice (with 2 different styles).
This consolidates the logging setup into a single helper and now both
autosynth's and synthtool's logger instance use the same configuration
(with different logger names).
This was included in #531, but can be standalone
=> fix: consolidate logging setup

synthtool/gcp/gapic_bazel.py
This will prevent the Kokoro machine from having too many bazel servers running the the background eating all the memory
=> fix: allow bazel server to run for 60 seconds idle

autosynth/multi.py, autosynth/synth.py, integration_tests/util.py, tests/test_multi.py, tests/testdata/multi-config.yaml, tests/testdata/sponge-log-golden.xml
Refactors `autosynth.multi` to update GitHub immediately after running `autosynth.synth` on a single library.
* Suppresses and logs errors if the GitHub issue management APIs fail.
* Fixes the case where if a GitHub API call fails, we crash the `autosynth.multi` run.
* Adds unit tests for all of `autosynth.multi`
=> fix: report autosynth status to GitHub early and don't crash on reporting

autosynth/synth.py
by cleaning up after each inner synth run
=> fix: avoid running out of disk space

autosynth/synth.py
=> fix: check for open PR before attemping single PR fallback with AUTOSYNTH_MULTIPLE_PRS

synthtool/gcp/templates/python_library/.kokoro/release.sh
=> chore(python): remove one remaining extra bash line

.kokoro-autosynth/node-apiary.yaml, .kokoro-autosynth/nodejs-apiary.cfg, config/node-apiary.yaml
A configuration file was lost during the copy from gerrit to github.
Fixes https://github.com/googleapis/synthtool/issues/567
=> fix: autosynth for nodejs-apiary

autosynth/synth.py
In Ruby's autosynth, some files cannot be cleaned up because, well, I don't know.  But Ruby isn't leaving gigabytes of garbage around so it's not a problem.  So if if git clean is not able to clean up every last file, that should not cause autosynth to file a bug.
Fixes https://github.com/googleapis/synthtool/issues/568
=> fix: don't fail when clean fails

synthtool/gcp/templates/java_library/.github/workflows/ci.yaml, synthtool/gcp/templates/java_library/README.md, synthtool/languages/java.py
Allows a repo maintainer to add a `min_java_version` in `.repo-metadata.json` which will:
* only run ci on Java 8+
* update the README accordingly
=> chore(java): allow overriding minimum supported Java version in templates

synthtool/gcp/templates/python_library/docs/conf.py.j2, synthtool/gcp/templates/python_library/noxfile.py.j2
=> docs: update python docs template

.kokoro-autosynth/php.cfg, .kokoro-autosynth/python.cfg
=> fix: longer autosynth timeouts for php and python

synthtool/gcp/templates/java_library/.github/CODEOWNERS
This should automatically request reviews from the googleapis/java-samples-reviewers team for changes to samples Java code.
If you provide a `codeowner_team` in the `.repo-metadata.json` configuration file, it also adds an entry for any Java code. Note that later entries in the file take precedence over earlier ones so samples Java code will only require reviews by the samples team.
=> chore(java_templates): add default CODEOWNERS files for samples reviews

synthtool/gcp/templates/java_library/renovate.json
=> chore: turn on renovate-bot master issue for java repos

synthtool/gcp/templates/java_library/.kokoro/build.sh
Let the samples test decide how to enforce linting
=> build(java): skip lint on samples directory

synthtool/README.md
`pip install -e .` did not work as expected on Justin's machine, and synthtool failed.
=> fix: switch back to using the PYTHONPATH statement

autosynth/multi.py
Links directly to the test log in sponge2
Example: http://sponge2/results/invocations/a84fe804-6b84-41a5-b1f2-e6d681e30fa2/targets/github%2Fsynthtool;config=default/tests;query=nodejs-dataproc;failed=false
=> fix: deep link into sponge2 which should contain the full output

autosynth/synth.py, autosynth/synthesizer.py
Fixes #612 
For the non-multiple commit, non-multiple pull request autosynth runs (Java and Elixir apiaries), we were incorrectly using the base directory as the log file. Now we write to the base_log_directory and optionally expand the path for additional args (used to specify which client we're generating in the Java/Elixir case) and finally specify sponge_log.log as the output file name.
=> fix: fix log path for single-commit, single-branch executions

synthtool/gcp/snippets.py, tests/fixtures/snippets/pom.xml
`[START_EXCLUDE]` and `[END_EXCLUDE]` region tags are standardized for snippets pulled into cloud.google.com.
=> feat: handle standardize START/END_EXCLUDE for snippets

synthtool/gcp/templates/java_library/.kokoro/build.sh, synthtool/gcp/templates/java_library/.kokoro/nightly/samples.cfg, synthtool/gcp/templates/java_library/.kokoro/populate-secrets.sh, synthtool/gcp/templates/java_library/.kokoro/presubmit/samples.cfg, synthtool/gcp/templates/java_library/.kokoro/trampoline.sh
Also use java-docs-samples user for samples tests.
Prototyped in https://github.com/googleapis/java-document-ai/pull/100. This API requires that the service account be owned by the project that is owns the resources.
=> ci(java): switch to secret manager from keystore

synthtool/gcp/templates/java_library/.kokoro/nightly/samples.cfg, synthtool/gcp/templates/java_library/.kokoro/presubmit/samples.cfg
Somehow an invisible character was copy/pasted into the file and Kokoro
cannot parse the file.
=> samples(java): fix bad character in samples.cfg from copy/paste

synthtool/gcp/templates/python_library/docs/conf.py.j2
-> Sphinx has  deprecated  the flag `autodoc_default_flags` in 1.8 version and now they are going to remove in `4.0` version and suggest alternative `autodoc_default_options`, found in their documentation   https://readthedocs.org/projects/sphinx/downloads/pdf/master/  and module is `7.5.13 Deprecated APIs`
-> This change is needed to solve Bigquey documentation issue https://github.com/googleapis/python-bigquery/issues/138
=> fix(python): change autodoc_default_flags to autodoc_default_options in python doc template

.kokoro-autosynth/common.cfg
nodejs timed-out last night after 3 hours
=> fix: set default timeout to 5 hours

synthtool/gcp/templates/java_library/.github/workflows/ci.yaml, synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
Executes the dependency tests on both Java 8 and Java 11 to prevent potential failures to go undetected when dependencies are only added for certain Java versions. See also https://github.com/googleapis/java-spanner/pull/281.
=> ci(java): run dependency test on Java 8 and 11

synthtool/gcp/templates/java_library/.github/workflows/ci.yaml, synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
This reverts commit 84f8ec7ff1885e00582b32a21cd21a481d25e591.
It broke the tests:
https://source.cloud.google.com/results/invocations/5c6ddabc-c5c9-43da-b82b-0d7313fbcbeb
=> Revert "ci(java): run dependency test on Java 8 and 11 (#633)"

synthtool/gcp/common.py, synthtool/languages/java.py, tests/test_language_java.py
This also fixes the Java template test to use local templates for the test.
=> feat: allow injecting template path as an argument

synthtool/gcp/gapic_bazel.py
For Node.js builds, postprocessing takes longer than a minute (`npm install`, linting, and formatting can be slow), so let's bump this idle timeout to 4 minutes to make sure the Bazel instance is reused. I'm not aware of any possible negative consequence of having this bumped.
=> fix: set idle timeout for bazel to 240 seconds

synthtool/gcp/templates/node_library/.gitattributes
=> fix: typo in nodejs .gitattribute

synthtool/gcp/common.py
if `cov_level` is not provided `common.py_library`, then it will be an undefined variable in [cover section in noxfile.py.j2](https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/noxfile.py.j2#L164). Therefore, `--fail-under={{ cov_level if cov_level != None else '100' }}` will become `--fail-under=` instead of `--fail-under=100`.
The fix is to set `cov_level` to None if not provided.
=> fix: fix cov_level issue

.kokoro-autosynth/nodejs.cfg
Recent kokoro jobs have been timing out after completing about 90% of the APIs.
=> fix: extend nodejs autosynth timeout by 2 hours

noxfile.py, requirements.txt, synthtool/metadata.py, synthtool/protos/metadata.proto, synthtool/protos/metadata_pb2.py, synthtool/protos/preconfig_pb2.py, tests/test_metadata.py
old strategy: observe file timestamps to see which files were touched
new strategy: use watchdog to observe every file system event
Control tracking obsolete files with an environment variable.
Fixes https://github.com/googleapis/synthtool/issues/216
=> fix: re-enable obsolete tracking with a new strategy

setup.py
#669 introduced watchdog, but did not add it to the list of dependencies installed when you install synthtool
=> fix(deps): add watchdog as declared dependency

requirements.txt
earlier versions will fail with the generated code
=> fix: require a recent version of protobuf

.kokoro-autosynth/nodejs-build.sh
This updates the build script to use `nvm` to always install the latest LTS releases of node.js and npm.  It's unclear if this will work in the kokoro environment and docker image, so we will need to iterate here.
=> fix(node): use nvm to install node in autosynth

synthtool/gcp/templates/java_library/samples/snippets/pom.xml
We are now only adding clients to libraries-bom once the client is
1.0.0. Since this template is created at repository creation time, we
don't want to include the libraries-bom installation method here.
Note: that this template is only added the first time - if a samples/snippets/pom.xml file exists, we leave the current file.
=> chore(java): default samples/snippets pom should not use libraries-bom

synthtool/gcp/templates/python_library/docs/conf.py.j2
This should fix build failures in python-bigquery.
Example:
https://github.com/googleapis/python-bigquery/pull/205
* also add a comment
=> chore(py_library): add some excludes in docs/conf.py

synthtool/README.md
=> docs: recommend installation via pip -e

synthtool/log.py
When the log level is set to DEBUG, watchdog spams the log making it unusable.
=> fix: reduce log level from DEBUG to INFO

synthtool/gcp/templates/node_library/.kokoro/release/publish.cfg
publication was still being performed on Node 8.
=> build: perform publish using Node 12

.kokoro-autosynth/ruby.cfg
After this PR is merged, Autosynth will generate a pull request for every synth.py in google-cloud-ruby.  That means roughly 80 PRs will arrive the next day.  Each PR will have the title "chore: start tracking obsolete files" and it will only contain changes to synth.metadata.
This will be a one-time nuisance.  After the 80 PRs are merged, no more such PRs will be generated.
=> chore: enable obsolete file tracking for Ruby

synthtool/metadata.py, tests/test_metadata.py
Elixir synth is failing for newly added libraries because synthtool is trying to start watchdog on a directory that doesn't exist yet because synth hasn't created it yet (see e.g. https://github.com/googleapis/elixir-google-api/issues/6174). This PR ensures the directory exists.
=> fix: Ensure watch_dir exists

synthtool/gcp/templates/java_library/.github/workflows/samples.yaml
Presubmit checks on GoogleCloudPlatform/java-docs-samples run these checks as optional checks.
=> chore(java_templates): add lint/static analysis presubmit checks for samples

synthtool/gcp/templates/java_library/.github/workflows/samples.yaml
This was creating too much noise. We will revisit with other options and/or tune these checks.
=> chore(java_templates): stop running pmd/spotbugs checks for samples

noxfile.py
A recent release of the black linting tool broke our automated lint.  Pin the version so it doesn't break periodically.
=> fix: pin black lint tool version

synthtool/gcp/templates/node_library/.kokoro/release/publish.cfg, synthtool/gcp/templates/node_library/.kokoro/samples-test.sh, synthtool/gcp/templates/node_library/.kokoro/system-test.sh, synthtool/gcp/templates/node_library/.kokoro/test.sh
Update build scripts:
* we will now report nightly build failures  as flaky tests .
* secrets are updated such that tagging/commenting should begin working: see: https://github.com/googleapis/releasetool/pull/262
_Note: combined these two updates so that I only face one mass PR tomorrow._
=> build: track flaky tests for "nightly", add new secrets for tagging

requirements.txt
Suggested solution for broken autosynth. https://github.com/googleapis/gapic-generator/issues/3271#issuecomment-686139564
=> fix: pin setuptools to 49.6.0

synthtool/gcp/templates/java_library/.github/CODEOWNERS
Default java repo ownership to yoshi-java.
=> chore(java): set yoshi-java as default CODEOWNER

synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
With required CODEOWNERS, use a bot user for approving PRs.
=> build(java): use yoshi-approver token for auto-approve

synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
since only release PRs should be evaluated for autorelease and also YOSHI_APPROVER_TOKEN cannot be shared on forked PRs.
=> chore(ci): skip autorelease workflow on non-release PRs

synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
since release-please bot sometimes proposes empty phantom release PRs (e.g. https://github.com/googleapis/java-cloud-bom/pull/973), we should be more resilient and check for file changes.
=> chore(ci): verify autorelease release PR content

synthtool/gcp/templates/python_library/.kokoro/samples/python3.6/common.cfg, synthtool/gcp/templates/python_library/.kokoro/samples/python3.7/common.cfg, synthtool/gcp/templates/python_library/.kokoro/samples/python3.8/common.cfg
https://github.com/googleapis/python-talent/blob/ef045e8eb348db36d7a2a611e6f26b11530d273b/samples/snippets/noxfile_config.py#L27-L32
`BUILD_SPECIFIC_GCLOUD_PROJECT` is an alternate project used for sample tests that do poorly with concurrent runs on the same project.
=> chore(python): use BUILD_SPECIFIC_GCLOUD_PROJECT for samples

autosynth/synth.py
Fixes #793 
When we specify a custom synth.py file, we should parse the AST from that file when determining which flags to set. Note that the parse_flags method already supported picking a file, we just need to use the user input.
=> fix: load flags from the specified synth.py file

synthtool/gcp/templates/java_library/README.md
Let the README generation handle all the versions to reduce churn.
Fixes #794
=> build(java): remove release-please version tags from README

synthtool/gcp/templates/java_library/.github/workflows/formatting.yaml
GitHub action config to run the java formatter and suggest inline fixes on the pull request.
This was tested in java-asset: [example PR](https://github.com/googleapis/java-asset/pull/392).
=> ci(java): suggest formatting fixes

synthtool/gcp/templates/python_library/.kokoro/test-samples.sh
Currently, `test-samples.sh` runs into a bug and crashes if the `./samples` directory doesn't exist in a repo. I'd argue that the check should pass automatically if there are no samples to test against. 
This would fix the issue we're running into on [python-logging](https://github.com/googleapis/python-logging), where no CI tests will pass until we merge the [PR adding samples](https://github.com/googleapis/python-logging/pull/67)
If we'd prefer having no samples to count as a test failure, I'd suggest we least add a better error message. Right now the code just crashes by trying to cd into a directory that doesn't exist
=> fix: samples tests should pass if no samples exist

synthtool/gcp/templates/java_library/.kokoro/build.sh
This is to reduce resource consumption since we often times hit resource quota limit in samples testing.
e.g. https://github.com/googleapis/java-bigquerydatatransfer/issues/410
=> ci(java): restrict presubmit samples ITs to only snapshot

synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Perform an installation of our `--production` dependencies first, with `--engine-strict`, so that we can detect dependencies that have dropped support for our supported Node.js version.
=> build: only check --engine-strict for production deps

autosynth/providers/ruby_apiary.py
This is an update to #802. The original idea was to pass a "flag" argument (`--clean`) down through synth to the underlying build script, for the one special synth job that deletes obsolete directories from the client. However, this confuses synthtool, which tries to parse the `--clean` argument itself (see https://github.com/googleapis/google-api-ruby-client/issues/1207). So instead I updated the build script to take `clean` as a non-flag argument, and we'll pass that instead. (An alternative approach might have been to pass `--` first, but I'm not sure if Python's arg parser recognizes that form, so I'll just go with the current approach that I know will work.)
=> fix: Use a non-flag arg for the ruby-apiary-clean synth job

.github/CODEOWNERS
Ending a path in star will only match files in that directory.
=> chore: remove `*` from owned dirs

synthtool/gcp/templates/java_library/renovate.json
To remove unused package groupings and add "test" commit type
=> chore: clean up and update renovate.json

synthtool/gcp/templates/java_library/.kokoro/build.sh
Fixes below error in Java repos when https://github.com/googleapis/synthtool/pull/804 was merged:
```
github/java-bigquerystorage/.kokoro/build.sh: line 81: pushd: {SAMPLES_DIR}: No such file or directory
```
Thanks @kolea2 for spotting this in Fusion build logs.
cc @chingor13
=> chore(ci): fix typo in restrict presubmit samples ITs to only snapshot

synthtool/gcp/templates/java_library/.kokoro/readme.sh
Exit code 28 is returned if no changes are required and should not be considered a failure.
=> chore(java): ignore return code 28 in README autosynth job

synthtool/gcp/common.py, tests/test_python_library.py
The python versions in the template have fallen behind the current versions of python. see https://python.org/downloads
=> test(python): fix template defaults for noxfile default py versions

synthtool/gcp/templates/java_library/.github/workflows/approve-readme.yaml, synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
So that renovate-bot stops proposing PRs like [this](https://github.com/googleapis/java-bigquerydatatransfer/pull/515/files)!
=> build(java): use actions/github-script v3 tag rather than full semver

synthtool/gcp/templates/java_library/.kokoro/common.sh, synthtool/gcp/templates/java_library/.kokoro/release/stage.sh
Tested: https://github.com/googleapis/java-container/pull/299 + https://github.com/googleapis/java-container/pull/303
It will now retry the staging portion of the release build up to 3 times.
Fixes https://github.com/googleapis/java-cloud-bom/issues/1241
=> chore(java): retry staging portion of the release with backoff

autosynth/change_pusher.py
This prevents autosynth from failing if the public description yields a PR title that is too long for github. (See #848)
=> fix: truncate new PR titles at 250 characters

synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc.sh
* add `export` to the envVar's to make sure maven knows about them.
* report the Java version
@tbpg FYI
=> chore: Update publish_javadoc.sh

autosynth/providers/apiary.py, tests/test_autosynth_apiary_provider.py
Fixes https://github.com/googleapis/google-api-java-client-services/issues/6646
=> fix(autosynth): apiary provider should include admin clients

synthtool/languages/python.py
For #210 
Always skip samples readmegen for now. Samples readmegen requires additional packages be installed through `pip install ...` to get the output of `python sample.py --help`. This is causing many Python synth generations to fail (#210).
=> fix(python): always skip samples readmegen

synthtool/gcp/templates/java_library/.github/generated-files-bot.yml
Depends on https://github.com/googleapis/repo-automation-bots/pull/1254
Fixes https://github.com/googleapis/repo-automation-bots/issues/1096
=> ci(java): ignore bot users for generate-files-bot

.kokoro-autosynth/dotnet-build.sh
Fixes #881 (somewhat hopefully)
=> fix: Update apt before installing apt-transport-https

autosynth/providers/ruby_apiary.py
The Ruby Apiary repo is moving the main google-api-client gem into a subdirectory as a first step toward splitting the monopackage. (See https://github.com/googleapis/google-api-ruby-client/pull/1821) This means the metadata files are also moving.
=> feat: Update Ruby Apiary metadata path to match Repo reorganization

autosynth/providers/apiary.py, tests/test_autosynth_apiary_provider.py
The Apiary provider was incorrectly interpreting discovery docs with names that have a version with a dot. For example [adexchangebuyer.v1.2.json](https://github.com/googleapis/discovery-artifact-manager/blob/master/discoveries/adexchangebuyer.v1.2.json). The current incorrect behavior would yield a library name of `adexchangebuyer.v1` and a version of `2` (because of the greedy nature of the regex). This was causing Ruby apiary synth to malfunction for these libraries.
Fixed by adjusting the regex to insist that the service name never has a period. Added a test.
/cc @chingor13 because this might affect Java Apiary synth as well.
=> fix: Listing apiary libraries correctly parses versions with dots

autosynth/providers/elixir.py
This is affecting the area120tables client, which Elixir is generating into the directory `area120_tables` but synthtool is trying to write the metadata file into `area120tables`, resulting in a synth failure (https://github.com/googleapis/elixir-google-api/issues/6707)
=> fix: Properly underscore elixir directory names with digits in the middle

noxfile.py
so our presubmit doesn't spontaneously break when mypy releases a new version.
Fixes:
https://github.com/googleapis/synthtool/issues/920
https://github.com/googleapis/synthtool/issues/919
=> fix: pin mypy to version 0.790

requirements.txt
Temporary fix for the broken python autosynth builds. (https://github.com/googleapis/gapic-generator/issues/3334)
The python microgenerator requires `google-api-core`. Because of a package import issue `google-api-core` is not being installed and Python autosynth jobs are failing. The workaround is to install the python generator [requirements](https://github.com/googleapis/gapic-generator-python/blob/master/requirements.txt) on the Python version that will be used by bazel.
From @vam-google:
> it is a really sophisticated python package import issue, which arises when multiple https://packaging.python.org/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages packages with the same namespace are used from bazel, and unfortunately gogole.api_core and protobuf are like …
=> build(python): install google-api-core for python generator

synthtool/gcp/templates/java_library/LICENSE
According to GitHub support, our Java repositories aren't detected as Apache-2.0 in their tooling due to the newline at the beginning of our LICENSE files:
https://github.com/googleapis/java-firestore/blob/master/LICENSE
This is annoying, but should get the GitHub API (and the UI) to report the correct license type.
=> chore: remove leading newline from LICENSE

synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
Noticed the workflow was getting skipped on all the release PRs. Updating due to recent update in release-please branch name.
=> build(java): update autorelease script

synthtool/gcp/pregenerated.py, synthtool/languages/java.py
Adds the ability to copy pregenerated code directly from `googleapis/googleapis-gen` rather than building it at runtime via bazel. This correctly can track the git source in synth.metadata and should allow autosynth to correctly binary search through history for context-aware-commits (googleapis and googleapis-gen have a 1:[0-1] relationship so history should be preserved).
Example `synth.py` for Java:
```python3
import synthtool.languages.java as java
service = 'domains'
versions = ['v1beta1']
for version in versions:
java.pregenerated_library(
service=service,
version=version,
path=f'google/cloud/{service}/{version}',
)
java.common_templates()
```
=> feat: add googleapis-gen as a tracked source

synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
This PR updates the GitHub Actions configuration for Linkage Monitor. Before this change, the CI configuration has "mvn install" command with 6 options. It turned out that a slight difference in the command line option from "build.sh" fails the build in google-auth-library-java repository (https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1941). (@Neenu1995 found the build failure. Thanks!) 
Therefore, this change updates the configuration so that Linkage Monitor job just uses "build.sh" to install the artifacts into local Maven repository.
I tested this change in java-spanner repository with this draft PR: https://github.com/googleapis/java-spanner/pull/868
It succeeded.
=> ci: linkage monitor CI job to use build.sh 

.dockerignore, docker/owlbot/nodejs/Dockerfile, docker/owlbot/nodejs/cloudbuild.yaml, docker/owlbot/nodejs/entrypoint.sh
Here's a sample owlbot.py that works with this docker image:
https://github.com/googleapis/nodejs-vision/blob/owlbot.py/owlbot.py
Observe that the call to `s.replace()` was not idempotent, so I had to add a conditional check to see if had already been applied.
=> feat: a docker image for owlbot's nodejs post processor

synthtool/gcp/templates/java_library/.kokoro/build.sh
@chingor13 This change keeps Maven 3.6.1 and later from spamming our CI logs with page after page of lists of artifacts it's downloading that makes it much harder to find the actual test output.
=> fix: don't log downloads

docker/owlbot/nodejs/Dockerfile, docker/owlbot/nodejs/cloudbuild.yaml, docker/owlbot/nodejs/entrypoint.sh, synthtool/languages/node.py
1. install linter when docker container is created.
2. introduce `postprocess_gapic_library_hermetic` which allows post processing to be run without an `npm install` step.
=> feat(owlbot): build linter into node container

synthtool/gcp/pregenerated.py
Autosynth may not reset the git clone of a given source - other
generators return a temp directory which contains the generated
code.
This fixes the case where autosynth is running the post processing
extra times on the same generated files and the post processing
step is not idempotent (e.g. adding a license header).
Fixes #957
=> fix: pregenerated code needs to return a copy

synthtool/languages/node.py
We were not linting `test`/`system-test`, which leads to linting issues, see: https://github.com/googleapis/nodejs-document-ai/pull/160
=> build(node): lint system-test and test

docker/owlbot/nodejs/entrypoint.sh, docker/owlbot/nodejs/restore_license_headers.sh
This script looks at the previous commit and current changes to see if any license headers changed. The heuristic for detecting the license header is a regex: `Copyright \d{4}` in the first 10 lines of the file. We compare the current version of the file against the version in the previous commit. If we find a copyright year in both versions and they have changed, we replace the copyright year with the one from the previous commit.
For now, this script can be included directly in the owl-bot post processor, but in the future could be put into its own dedicated post-processor if owl-bot supports multiple post processors.
=> fix(owl-bot): add script that reverts license year changes

docker/owlbot/java/bin/entrypoint.sh, docker/owlbot/java/bin/fix_license_headers.sh, docker/owlbot/java/src/fix-license-headers.py
Note this requires #1008 or if run after synthtool generation, we will duplicate license headers.
=> fix(owlbot-java): after copying code, fix the license headers

docker/owlbot/python/Dockerfile
The owlbot post processor is failing in googleapis/python-artifact-registry/pull/11 with the following error:
```
nox > Running session blacken
nox > Session blacken failed: Python interpreter 3.6 not found.
2021-04-05 21:15:39,278 synthtool > Failed executing nox -s blacken:
None
```
If I change the base image to `python:3.6.13-buster` in the Dockerfile, I no longer see the failure. Python 3.6 is required for the nox blacken session.
https://github.com/googleapis/python-artifact-registry/blob/master/noxfile.py#L65
=> chore: Use python 3.6.13-buster for owlbot post-processor

.github/CODEOWNERS
Add the additional `@googleapis/github-automation` team as owner.
=> meta: add  @googleapis/github-automation as owner

docker/owlbot/python/Dockerfile, synthtool/__init__.py, synthtool/languages/python.py, synthtool/transforms.py, tests/test_transforms.py
Almost every synth.py for a Python library has naughty code.  So there's no hope of Python repos without owlbot.py files.  Instead, we'll replace the call to gapic.py_library() with a call to get_staging_dirs().
=> feat: expose get_staging_dirs() for Python

docker/owlbot/nodejs/Dockerfile, synthtool/gcp/common.py, synthtool/languages/node.py, tests/fixtures/nodejs-dlp-with-staging/owl-bot-staging/v2/src/index.ts, tests/fixtures/nodejs-dlp-with-staging/src/index.ts, tests/test_node.py
Should greatly simplify migrations.
Used the word "excludes" instead of "ignores" because existing synth.py files already use the term "excludes", so using the word "ignores" would make migrating more tedious, error-prone, and confusing.
Example of a migrated repo:
https://github.com/googleapis/nodejs-ai-platform/compare/owl-bot?expand=1
Also fixed a bug where `generate_index_ts()` was called even when `"src/index.ts"` was in the exclude list.
=> feat: add excludes and patch callback arguments to owlbot_main

synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
Java 11 started failing the build on javadoc lint issues which are unrelated to the dependencies test. Java 8 is not failing (which is the version we run javadoc builds on).
Example failure: https://github.com/googleapis/google-api-java-client/pull/1748/checks?check_run_id=2304526771
=> build(java): skip javadoc tests during dependencies test

synthtool/gcp/templates/java_library/.kokoro/release/snapshot.sh, synthtool/gcp/templates/java_library/.kokoro/release/stage.sh
`mvn deploy` will run `mvn install` so specifying `mvn install deploy` is redundant at best. At worst, it will cause plugins like maven-shade-plugin to be executed twice re-shading itself
=> fix: release scripts from issuing overlapping phases

docker/owlbot/java/bin/write_templates.sh
Should prevent owl-bot from making "empty" synth.metadata updates
=> fix(owlbot-java): run owlboy.py directly rather than via synthtool module

synthtool/transforms.py, tests/test_transforms.py
This test was previously failing flakily because the listing of directories is not guaranteed to be sorted. We should be consistent in what gets returned.
In most cases, this won't matter for synthtool users, but we should do our best to be consistent between runs.
=> fix: get_staging_dirs() should return a consistent ordering

docker/owlbot/python/cloudbuild.yaml
I've confirmed that this works locally by running
```
gcloud builds submit --config=docker/owlbot/python/cloudbuild.yaml --substitutions=SHORT_SHA=$(git rev-parse --short HEAD)
```
Then I ran `python -v` in the docker container using 
```
docker run --rm -it --entrypoint /bin/bash <image>
```
=> chore: Fix python owlbot post processor image cloudbuild.yaml

tests/test_common.py, tests/test_language_java.py, tests/test_node.py, tests/test_partials.py, tests/test_python_library.py, tests/test_samples.py, tests/test_snippets.py, tests/test_transforms.py, tests/test_util.py, tests/util.py
* `util.chdir(path)` - changes the current working directory and restores the original
* `util.copied_fixtures_dir(path)` - copies an entire directory to a new temporary directory, chdirs into that directory, and restores the original current working directory
These are 2 very common test setups that are used across the tests in this repository. It will help us ensure that we are correctly restoring the cwd between tests.
=> refactor(test): add util.chdir, util.copied_fixtures_dir contextmanagers to clean up tests

synthtool/languages/java.py
This prevents synthtool from removing the branch setup for lts support
=> chore: ignore release-please.yml if it already exists

synthtool/gcp/templates/java_library/.github/release-please.yml, synthtool/languages/java.py, tests/fixtures/java_templates/release-please-update/.github/release-please.yml, tests/fixtures/java_templates/release-please-update/.repo-metadata.json, tests/test_language_java.py
Requires https://github.com/googleapis/releasetool/pull/323 to be merged first
If no `.github/release-please.yml` exists, create one from the template.
If one does exist, set `handleGHRelease` to `true` for the main config and each configured branch.
See https://github.com/googleapis/repo-automation-bots/tree/master/packages/release-please#configuration for config file structure.
This is part of go/deprecate-autorelease-tag where we switch from autorelease tagging to release-please tagging.
=> build(java): switch to release-please for release tagging

synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc11.sh
Fixes b/179912573
Adds cross reference links to docs. Currently will only link to the latest version of the library, but will revisit versioning as we address versioning for docs. http-client and protobuf don't have generated xrefs yet, but docpipline will skip those until we do.
Tested this out on a few repos and appears to be working as intended.
=> chore: adding cloud-rad java xrefs

setup.py
This fixes synthtool in our owlbot-java image which is using an older version of python.
This is for the same error we fixed in releasetool. https://github.com/googleapis/releasetool/pull/333
=> fix(deps): lock click to 7.x

.kokoro-autosynth/build.sh
The code was still being fully generated, but the kokoro jobs were marked as failures because a kokoro tool failed.  See b/187701234 for more details.
=> fix: broken rsync and end of kokoro build jobs

synthtool/languages/node.py
… no versions to post process.
Fixes one more way `owlbot_main()` choked on repos without source code from googleapis-gen.
Fixes https://github.com/googleapis/repo-automation-bots/issues/1600
=> fix: don't invoke postprocess_gapic_library_hermetic() when there are

synthtool/languages/node.py
Fixes https://github.com/googleapis/synthtool/issues/1103
=> fix: make `generate_index_ts()` deterministic

docker/owlbot/java/src/fix-poms.py
Java-gsuite-addons has an extra set of protos that other protos in the library depend on. These are added to the repo as a separate module `proto-google-apps-script-type-protos`. Only proto-google-cloud-gsuite-addons-v1 depends on this module. But owlbot is currently configured to add all modules to its parent pom. Since the parent do not depend on this extra protos module, it fails the dependency check.
To solve this issue, the post-processor is being configured to add only the modules with a version (v1 or v2) in it.
=> chore(owlbot-java): only add modules with version v1 or v2 to parent pom

synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
Tested on pubsublite, bigquery https://github.com/googleapis/java-bigquery/pull/1373 and bigquerystorage https://github.com/googleapis/java-bigquerystorage/pull/1133, no breakages
=> fix: Update dependencies.sh to not break on mac

synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
This prevents processing the unexpanded glob "**/.flattened-pom.xml" in repos which do not flatten any POMs.
=> fix: Add `shopt -s nullglob` to dependencies script

.kokoro-autosynth/build-in-docker.sh
One of the nicer code formatting tools I've found for PHP is, interestingly enough, written in node: https://github.com/prettier/plugin-php
I was hoping to use it as part of our synth scripts to help smooth over some recent changes from the microgenerator. Ultimately I think I'd like to work this into the microgenerator, but am hoping this would be an acceptable alternative until then.
These additions are copied over from [node's build file](https://github.com/googleapis/synthtool/blob/master/.kokoro-autosynth/nodejs-build.sh#L20-L34) and based upon reviewing the changes [here](https://github.com/googleapis/synthtool/pull/1063/files). If there is a more appropriate way to achieve this here or we'd prefer to have a separate build file for PHP, please let me know, but it seemed relatively …
=> build: enable npm for php/python builds

synthtool/gcp/common.py, tests/test_common.py
First step to fixing https://github.com/googleapis/repo-automation-bots/issues/2098.
I want to observe the default branch in the first cloud build step,
then pass it to a later step.  However, it can't be passed directly
via an environment variable because steps can't modify their environment
variables and it's not possible to dynamically compose an environment
variable in a cloud-build.yaml.
Therefore, I'll observe the default branch and record it in a file, and
then pass it the file path to the later step.  The contents of the file
may change but the path to the file is constant and can be specified
in cloud-build.yaml.
=> feat: add env var DEFAULT_BRANCH_PATH

.kokoro-autosynth/build-in-docker.sh
Follows: https://github.com/googleapis/synthtool/pull/1138. The latest build failed with `.kokoro-autosynth/build-in-docker.sh: line 49: sudo: command not found` - it should be safe to remove as we likely already have root in the container.
=> chore: remove sudo usage

synthtool/gcp/templates/java_library/java.header
After discussion with OSPO, it has been decided to remove "All rights reserved" clause from the java.header file to better reflect the [correct license header](https://g3doc.corp.google.com/company/teams/opensource/releasing/preparing.md?cl=head#Apache-header).
=> chore: remove All rights reserved clause from java.header

.kokoro-autosynth/ruby.cfg
I've determined that Ruby autosynth jobs that use Bazel are taking far too long, sometimes up to an hour _per library_, causing autosynth to timeout. The problem is that some synth jobs need to run large numbers (up to dozens) of gapic generation bazel builds, against different commits from googleapis. For Ruby, many older commits from googleapis have incomplete, buggy, or unoptimized bazel configurations that will either fail to build in spectacular ways, or (worse) result in long-running bazel jobs that (among other things) download and build the Ruby VM from source. When there are dozens of such bazel builds in a single synth job, it becomes clear why the overall synth job will eventually timeout. [Example log (internal-only link)](https://fusion.corp.googleusercontent.com/file/autoview …
=> fix(ruby): Disable multi-commits for Ruby bazel autosynth

synthtool/languages/java.py
There are cases when generating a library the gapic directory prefix should be preserved (veneer clients for example). This feature adds a new parameter `preserve_gapic` to `java.gapic_library` and `java.bazel_library`
=> chore: add preserve_gapic to java library generation options

synthtool/gcp/templates/java_library/README.md
Fixes googleapis/java-logging#586.
Since no java repos have README in samples/ subfolder, we remove the mentioning from README
=> chore(docs): remove mention about samples README

synthtool/gcp/templates/java_library/README.md
as a part of the PR 582 for java-logging an authorization section is added to the Java README template.
Fixing googleapis/java-logging#570.
=> chore(docs): add Authorization section to Java README template

synthtool/gcp/templates/java_library/.kokoro/build.sh, synthtool/gcp/templates/java_library/.kokoro/nightly/integration.cfg, synthtool/gcp/templates/java_library/.kokoro/nightly/samples.cfg
Kokoro job config now supports both environment variables during this migration period.
=> build(java): use ENABLE_FLAKYBOT env variable

synthtool/log.py
lint-3.6 check was failing in master branch of synthtool with the following error.
```
synthtool/log.py:21: error: Cannot assign to a type
synthtool/log.py:21: error: Incompatible types in assignment (expression has type "None", variable has type "Type[ColoredFormatter]")
synthtool/log.py:71: error: Incompatible types in assignment (expression has type "Formatter", variable has type "ColoredFormatter")
Found 3 errors in 1 file (checked 47 source files)
nox > Command mypy synthtool autosynth failed with exit code 1
nox > Session lint-3.6 failed.
```
=> chore: fix log.py from failing lint-3.6 check

synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
Gitbub Action updated LTS([18.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md), [20.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md)) versions of Github-Hosted runners for Ubuntu with the latest version of Apache Maven. The new version of Ubuntu has `Apache Maven 3.8.2` which is incompatible with `flatten-maven-plugin:1.2.7`. This caused all github actions using the latest Ubuntu version to fail.
```
Error:  Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.2.7:flatten (flatten) on project google-cloud-bigquery: failed to create a clean pom: unable to create flattened dependencies: caught exception when flattening dependencies: Failed to read artifact descriptor for …
```
=> chore(java): install maven 3.8.1 at runtime

synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
to install maven 3.8.1 at runtime too (related to #1202)
Tested in [java-bigquerystorage](https://github.com/googleapis/java-bigquerystorage/pull/1291/commits/7834f4ff86858f6ed0b8068ea66dadf6365e399a)
=> chore(java): update windows build

synthtool/gcp/templates/java_library/.github/workflows/ci.yaml, synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
* update dependencies.sh to not pass MaxPermSize when jdk 17 is used. MaxPermSize is an unrecognized flag in jdk 17.
A prototpe of these changes has been tested in https://github.com/googleapis/java-storage/pull/1016
=> build: add jdk 17 to java units and dependency builds

synthtool/gcp/common.py, synthtool/languages/python.py, tests/test_common.py
PR #1246 added ability to detect versions recursively when `detect_versions()` is called, however we're seeing erroneous versions detected in python-webrisk [here](https://github.com/googleapis/python-webrisk/pull/137/files#diff-8d068e8797e88947c320f79e856c3e16a72b730124a8f9d7031e2c4680dfa534R22).
I've updated the code to stop searching subdirectories if versions are found in the parent directory. I've also added a test to confirm the behaviour.
With the code in #1246, the following versions are detected.
```
webrisk_v1
webrisk_v1beta1
web_risk_service_v1_beta1 <- this is erroneously detected, and it is actually a service under webrisk_v1beta1
```
With the code in this PR, the following versions are detected
```
webrisk_v1
webrisk_v1beta1
```
=> chore(python): fix erroneous versions detected in detect_versions()

synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
Let's let all the unit tests complete for now.  Java 17 isn't quite ready.
=> chore(java): update ci.yaml

synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
java-format requires JRE v11+ to run linter. It still check older code, just jre has to be 11+: https://github.com/google/google-java-format/issues/529
Updating ci.yaml template since it is applicable for all the libraries.
=> chore: update jre to 11 for linter

synthtool/gcp/common.py
The [python-recaptcha-enterprise](https://github.com/googleapis/python-recaptcha-enterprise) requires a custom Dockerfile for samples testing. This PR eliminates the need to set the `custom_samples_dockerfile` argument of `py_library` which is currently done in owlbot.py [here](https://github.com/googleapis/python-recaptcha-enterprise/blob/main/owlbot.py#L42). IOW, kwargs `custom_samples_dockerfile` will automatically be set to `True` if the following file exists: `/.kokoro/docker/samples/Dockerfile`.
I tested the changes using the following commands after cloning synthtool
```
git checkout automatically-detect-when-samples-require-custom-dockerfile
docker build -f docker/owlbot/python/Dockerfile -t customdockerfile . 
```
Once the docker image was built, I ran the following commands in …
=> chore(python): detect when samples testing requires custom dockerfile

synthtool/languages/python.py
Many python repositories have a separate `noxfile.py` file in the `samples` directory. This PR modifies `owlbot_main()` for python to run the `blacken` nox session on all directories that contain a `noxfile.py` rather than only the root of the repository.
I tested the changes using the following commands after cloning synthtool
```
git checkout run-blacken-session-for-all-dirs
docker build -f docker/owlbot/python/Dockerfile -t runblackenonsamples . 
```
Once the docker image was built, I ran the following commands in the root of python-apigee-connect which has no samples and python-secret-manager which has samples. I've confirmed that the blacken session runs on all directories that have `noxfile.py`.
```
docker run --user $(id -u):$(id -g) --rm -v $(pwd):/repo -w /repo …
```
=> chore(python): run blacken session for all directories with a noxfile

synthtool/gcp/common.py
In https://github.com/googleapis/python-datacatalog/issues/153 we discovered that Markdown does not support certain formatting options, like tables when rendered from Sphinx.
=> chore(python): include UPGRADING.rst if it exists

docker/owlbot/java/Dockerfile, docker/owlbot/java/container_test.yaml
Fixes https://github.com/googleapis/synthtool/issues/1287
https://github.com/googleapis/java-shared-config/pull/361 sets the google-java-format version 1.13.0.  Timur already committed the Java version upgrade for the linter. https://github.com/googleapis/synthtool/commit/42a3786737c17ece39924d7025f3be481812da53
As per @chingor13 , the formatter version was previously pinned to the old formatter because of Java 7 support.
=> deps: upgrade google-java-format to 1.13.0

synthtool/gcp/templates/java_library/.kokoro/build.sh
This adds the -ntp flag to native image testing command to produce more readable test log outputs.
=> fix(java): Add -ntp flag to native image testing command

synthtool/gcp/templates/java_library/.kokoro/build.sh
This passes integration test args to the native image testing command in order to capture integration test settings from repo tests.
Will fix GraalVM breakages for https://github.com/googleapis/java-redis
=> fix(java): Pass integration test flags to native image testing

synthtool/languages/php.py
https://github.com/googleapis/google-cloud-php/pull/5061 exposed an issue with copying over generated metadata during the post processing job.
Generated protos rely on a php_namespace setting where we have a convention of lower casing the words alpha, beta, etc. in a version string. The generated metadata, on the other hand, does not follow these rules and is generated using a capital letter for these strings (e.g., Alpha, Beta).
This fix makes the directory check case insensitive, which should allow us to pick up the metadata directory in post processing for any packages which have alpha or beta qualifiers.
Please let me know if you would like for this change to include a set of further fixtures alongside https://github.com/googleapis/synthtool/tree/master/tests/fixtures/php/php_asset to …
=> fix: make version check case insensitive

synthtool/gcp/templates/java_library/.github/sync-repo-settings.yaml
Towards https://github.com/googleapis/repo-automation-bots/issues/2112
This file is only created upon initial generation. This will make it required for newly generated repositories.
=> build: make OwlBot check required

synthtool/gcp/templates/java_library/.github/PULL_REQUEST_TEMPLATE.md
@lesv During today's meeting @BenWhitehead had an idea to reference the SAMPLE_FORMAT.md in the pull request template. What do you think?
=> ci: pull request template includes sample format

docker/owlbot/java/templates/poms/cloud_pom.xml.j2, docker/owlbot/java/tests/new-client/golden/google-cloud-foo/pom.xml, synthtool/gcp/templates/java_library/.kokoro/common.sh
Adding in new dependencies into the template that are needed for REGAPIC. 
This change should also trigger an update to all repos to use the latest version of the postprocessor image.
=> chore: update dependencies for regapic

synthtool/gcp/templates/java_library/.github/sync-repo-settings.yaml
The Java repository template does not require clirr any more.
=> feat: java template no longer require clirr

docker/owlbot/java/bin/entrypoint.sh
Updating OwlBot Java Postprocessor (owlbot-java) to work for monorepo (google-cloud-java).
Here are 3 example commits in 3 pull requests with my local Dockerfile build:
- https://github.com/googleapis/google-cloud-java/pull/8026/commits/6ce601572bf85cf4b2e7da4de6716a2342c0c4b2
- https://github.com/googleapis/google-cloud-java/pull/8020/commits/83d0bffc36989e4c191522ff4a3e9972343183e1
- https://github.com/googleapis/google-cloud-java/pull/8018/commits/00ec0a09e314b1a1f5c8ad00465bfb27aff231fa
(In the pull request check, OwlBot Postprocessor was failing because I didn't update the owlbot-java image used in the check yet)
Here is how I tested this change:
```
$ git pull && docker build -f docker/owlbot/java/Dockerfile .
...
Successfully built 07d37702324a
```
```
$ gh pr checkout 8026
$ …
```
=> ci: adjust owlbot-java for monorepo

synthtool/gcp/templates/java_library/.kokoro/requirements.in, synthtool/gcp/templates/java_library/.kokoro/requirements.txt
Verified that certifi 2022.9.24 and google-resumable-media 2.3.3 support Python 3.6. See https://pypi.org/project/google-resumable-media/ and https://pypi.org/project/google-resumable-media/2.3.3/
=> chore: pin versions of certifi and google-resumable-media 

synthtool/gcp/templates/java_library/.kokoro/requirements.in, synthtool/gcp/templates/java_library/.kokoro/requirements.txt
Using the latest version of gcp-docuploader (0.6.4) was resulting in:
```
Traceback (most recent call last):
File "/root/.pyenv/versions/3.6.12/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/root/.pyenv/versions/3.6.12/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/docuploader/__main__.py", line 26, in <module>
from docuploader.protos import metadata_pb2
File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/docuploader/protos/metadata_pb2.py", line 5, in <module>
from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder'
cleanup
```
It looks like the latest version requires a newer version of the protobuf dependency …
=> chore: use gcp-docuploader 0.6.3

synthtool/gcp/templates/java_library/.kokoro/build.sh
The opting in of tests for native image testing is explicitly done in the `native` profile's maven-surefire-plugin. See https://github.com/googleapis/java-shared-config/blob/44a77b0faf5b4f3f9208117ccab0a3717d059efd/pom.xml#L806-L817 for reference. Therefore, the `-Penable-integration-tests` profile is redundant.
=> chore(java): omit `-Penable-integration-tests` parameter from native image test run command

synthtool/gcp/templates/java_library/README.md, synthtool/languages/java.py
The README.md files in the google-cloud-java monorepo to have instructions about how to use the Libraries BOM. This is part of b/274518727.
I built the Docker image:
```
suztomo@suztomo:~/synthtool$  docker build -f docker/owlbot/java/Dockerfile .
...
Successfully built d50554d0e398
```
In google-cloud-java clone, I touched different Java files in java-api-gateway, java-language and java-notification.
```
for M in java-api-gateway java-language java-notification; do
echo "" >> $(find $M -name '*.java' |head -1)
done
git commit -a -m 'chore: touch files to invoke OwlBot post processor'
```
Then I ran the code with google-cloud-java repository:
```
suztomo@suztomo:~/google-cloud-java$ docker run --rm -v $(pwd):/workspace  fd14d77283ae
```
The three modules got the channge in their README …
=> chore: README template fix in google-cloud-java

synthtool/gcp/templates/java_library/.github/dependabot.yml
Dependabot `ignore` feature: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
=> chore: Update `dependabot.yml` template

synthtool/gcp/templates/java_library/.github/sync-repo-settings.yaml, synthtool/gcp/templates/java_library/.github/workflows/ci.yaml, synthtool/gcp/templates/java_library/.kokoro/build.sh
It worked in https://github.com/googleapis/java-storage/pull/2081 (closed after confirming it works).
* Our Java projects are configured to produce Java 8-compatible bytecode via https://github.com/googleapis/java-shared-config/blob/main/pom.xml#L848. This change ensures this config is applied correctly.
* This change also switches the JDK distribution of GitHub Actions to temurin from zulu.
* For the repositories that mark "dependencies (8)" and "dependencies (11)" as required, they should point to only "dependencies (17)" via `.github/sync-repo-settings.yaml`. I'll create pull requests to the repositories, or add necessary commit to derived owl-bot-update-lock pull requests.
=> chore: Java 8 unit test to build code in Java 17 and run tests on Java 8

synthtool/gcp/templates/java_library/.github/sync-repo-settings.yaml, synthtool/gcp/templates/java_library/.github/workflows/ci.yaml, synthtool/gcp/templates/java_library/.github/workflows/samples.yaml
This also changes the JDK distribution from zulu to temurin
https://github.com/actions/setup-java#eclipse-temurin
=> ci: javadoc job (JDK 17) in ci.yaml

synthtool/gcp/templates/java_library/.github/workflows/renovate_config_check.yaml
Introducing config checker for renovate bot upon every pull request touching `renovate.json`.
=> chore: Create renovate_config_check.yaml

synthtool/gcp/templates/java_library/renovate.json
In this PR:
- Add a regex custom manager to match unmanaged dependency check version update in lockstep with sdk-platform-java-config update.
=> chore: add regex to match unmanaged dependency check

synthtool/gcp/templates/java_library/renovate.json
In this PR:
- Update renovate config to explicitly ignore workflow files in `.github/workflows`.
Context: we want to use renovateBot to update the version of unmanaged dependency check in `.github/workflows/unmanaged_dependency_check.yaml`. However, the directory is ignored in renovate config (#1855). Explicitly list files in this directory can make renovate include `.github/workflows/unmanaged_dependency_check.yaml`.
=> chore: update ignore paths in renovate config

synthtool/gcp/templates/java_library/.github/trusted-contribution.yml
From reading the configuration (https://github.com/googleapis/repo-automation-bots/pull/1682/files), it accepts multiple objects.
=> ci: automatic kokoro label in and /gcbrun comment
